export type Tier = "S" | "A" | "B";

export type EventStatus = "upcoming" | "live" | "completed" | "cancelled";

export type EventCost = {
  flight: number;
  hotel: number;
  transport: number;
  meals: number;
  ticket: number;
  total: number;
  note?: string;
};

export type Company = {
  name: string;
  tags: string[];
  people: string[];
  role: string;
  isNew?: boolean;
  layer?: string; // "L1" | "L2" | "Infra" | "DeFi" | "CEX" | "VC" etc.
  tgeDone?: boolean; // TGE 완료 여부
  tgeNote?: string; // TGE 관련 메모
};

export type EventData = {
  id: string;
  name: string;
  city: string;
  country: string;
  date: string;
  endDate?: string;
  days: number;
  venue?: string;
  tier: Tier;
  autoTier: Tier;
  tierScore: number;
  tierReasons: string[];
  gradient: string;
  status: EventStatus;
  isDomestic?: boolean;
  cancelReason?: string;
  imageUrl?: string;
  sideEventUrl?: string;
  sideEventSourceUrl?: string;
  website?: string;
  cost: EventCost;
  summary: Record<"features" | "difference" | "pros" | "risks" | "expectations", string[]>;
  feed: { label: string; time: string; type: string }[];
  archive: {
    year: string;
    eventTitle: string;
    attendees: string;
    sideEvents: number;
    sponsors: number;
    media: number;
    notes: string[];
  };
  kpis: { label: string; value: string; detail: string }[];
  budget: { label: string; value: number }[];
  sideEventTrend: { label: string; value: number }[];
  actions: string[];
  companies: Company[];
  sideEvents: {
    count: number;
    label: string;
    items: { name: string; host: string; date: string; desc: string; url?: string }[];
  };
};

const eventData: EventData[] = [
  {
    id: "bitcoin-2026",
    name: "Bitcoin 2026",
    city: "Las Vegas",
    country: "United States",
    date: "2026-04-27",
    endDate: "2026-04-29",
    days: 3,
    venue: "The Venetian",
    tier: "S",
    autoTier: "S",
    tierScore: 95,
    tierReasons: ["세계 최대 비트코인 이벤트", "500+ 연사", "5,000+ 기업 참여"],
    gradient: "from-orange-100 via-white to-amber-100",
    status: "completed",
    imageUrl: "https://images.unsplash.com/photo-1581351721010-8cf859cb14a4?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/bitcoin-2026",
    website: "https://b.tc/conference",
    cost: { flight: 1050, hotel: 1380, transport: 200, meals: 480, ticket: 899, total: 4009, note: "Pro Pass 기준. General Admission은 ~$349" },
    summary: {
      features: ["세계 최대 규모 비트코인 컨퍼런스", "채굴, 에너지, 정책, 기업 트랙 등 다양한 트랙 구성", "5,000+ 기업, 500+ 연사 참여"],
      difference: ["비트코인 단일 자산 집중 - 다른 프로토콜 없음", "채굴 및 에너지 인프라에 특화", "정책 및 국가 채택 논의가 핵심"],
      pros: ["비트코인 생태계 전체를 아우르는 최고의 자리", "채굴/에너지/정책 네트워킹 기회 풍부", "글로벌 미디어 관심도 높음"],
      risks: ["비트코인 외 프로토콜 관련성 낮음", "VIP/Whale Pass가 접근성 제한할 수 있음", "라스베이거스 호텔 가격 변동 큼"],
      expectations: ["채굴 인프라 파트너십 논의", "국가/기업 비트코인 자산 전략", "정책 및 규제 동향 파악"],
    },
    feed: [
      { label: "행사 종료 (Day 3)", time: "2026-04-29", type: "완료" },
      { label: "채굴 트랙 스피커 발표 완료", time: "2026-04-28", type: "연사" },
      { label: "엔터프라이즈 홀 폐관", time: "2026-04-29", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "35K+",
      sideEvents: 180,
      sponsors: 300,
      media: 120,
      eventTitle: "Bitcoin 2025",
      notes: ["채굴, 트레저리 채택, 미국 정책 관심에서 가장 강한 시그널", "500+ 연사, 5,000+ 기업 참여 규모"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "채굴/정책/인프라" },
      { label: "아카이브 성장", value: "+22%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "3시간", detail: "행사 진행 중" },
    ],
    budget: [
      { label: "항공권", value: 1050 },
      { label: "숙박", value: 1380 },
      { label: "티켓", value: 899 },
      { label: "현지비", value: 680 },
    ],
    sideEventTrend: [
      { label: "2023", value: 110 },
      { label: "2024", value: 155 },
      { label: "2025", value: 180 },
      { label: "2026", value: 180 },
    ],
    actions: ["행사 진행 중 - 라이브 피드 모니터링", "엔터프라이즈 트랙 세션 확인", "채굴 스폰서 부스 방문 계획"],
    companies: [
      { name: "Blockstream", tags: ["Bitcoin", "Infra"], people: ["Partnership Lead"], role: "인프라 파트너십", isNew: true, layer: "L1", tgeDone: false, tgeNote: "Bitcoin L1, 토큰 없음 (BTC 자체)" },
      { name: "Marathon Digital", tags: ["Mining"], people: ["IR Lead"], role: "채굴 시장 동향", layer: "Mining", tgeDone: true, tgeNote: "MARA 상장" },
      { name: "Strike", tags: ["Payments"], people: ["BD Lead"], role: "결제 레일", layer: "Lightning", tgeDone: false, tgeNote: "Lightning 기반, 별도 토큰 없음" },
      { name: "Galaxy Digital", tags: ["Finance", "Mining"], people: ["Research Lead"], role: "시장 분석", layer: "Finance", tgeDone: true, tgeNote: "GLXY 상장" },
    ],
    sideEvents: {
      count: 180,
      label: "사이드 이벤트",
      items: [
        { name: "Bitcoin Policy Summit", host: "Bitcoin Foundation", date: "2026-04-27", desc: "비트코인 정책 및 규제 포럼" },
        { name: "Mining & Energy Summit", host: "Marathon Digital", date: "2026-04-28", desc: "채굴 인프라 및 에너지 효율성" },
        { name: "Lightning Hackathon", host: "Strike + Voltage", date: "2026-04-27", desc: "라이트닝 네트워크 개발자 해커톤" },
        { name: "Institutional Bitcoin Workshop", host: "Galaxy Digital", date: "2026-04-29", desc: "기관 비트코인 자산 전략" },
      ],
    },
  },
  {
    id: "token2049-dubai",
    name: "TOKEN2049 Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    date: "2026-04-29",
    endDate: "2026-04-30",
    days: 2,
    venue: "Madinate Jumeirah (예상)",
    tier: "S",
    autoTier: "S",
    tierScore: 90,
    tierReasons: ["글로벌 최대 크립토 이벤트 시리즈", "15,000+ 참석자 예상", "4,000+ 기업"],
    gradient: "from-amber-100 via-white to-cyan-100",
    status: "cancelled",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/dubaievents/map",
    website: "https://www.token2049.com/",
    cancelReason: "이란-중동 분쟁으로 인한 안전 문제로 2027년 4월로 연기",
    cost: { flight: 760, hotel: 1280, transport: 160, meals: 330, ticket: 799, total: 3329 },
    summary: {
      features: ["글로벌 최대 규모 크립토 이벤트", "자본 및 거래소 집중 참여", "프리미엄 스폰서 밀도 높음"],
      difference: ["기관 중심, 개발자 중심 아님", "중동/북아프리카 진출 시그널 강함", "시니어 BD에 적합"],
      pros: ["짧은 일정으로 효율적", "펀드/거래소 밀도 높음", "두바이 호스피탈리티 생태계 우수"],
      risks: ["2026년 행사 취소 - 2027년으로 연기", "프리미엄 패스 업셀로 접근성 제한 가능", "호텔 가격 빠르게 변동"],
      expectations: ["2027년 재개 시 참고용", "거래소 파트너십 사전 식별", "중동 확장 대화"],
    },
    feed: [
      { label: "2027년 4월로 연기 확정", time: "2026-03-14", type: "공지" },
      { label: "이란 미사일 위협으로 안전 우려", time: "2026-03-13", type: "안전" },
      { label: "행사 티켓 매진 후 취소", time: "2026-03-12", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "15K+",
      sideEvents: 500,
      sponsors: 210,
      media: 88,
      eventTitle: "TOKEN2049 Dubai 2025",
      notes: ["자본, 거래소, 시장 구조, 중동 정책 대화에 강점", "500+ 사이드 이벤트, 기관 참여 높음"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "자본/거래소" },
      { label: "아카이브 성장", value: "+24%", detail: "스폰서 YoY" },
      { label: "상태", value: "취소", detail: "2027년 연기" },
    ],
    budget: [
      { label: "항공권", value: 760 },
      { label: "숙박", value: 1280 },
      { label: "티켓", value: 799 },
      { label: "현지비", value: 490 },
    ],
    sideEventTrend: [
      { label: "2023", value: 90 },
      { label: "2024", value: 150 },
      { label: "2025", value: 500 },
      { label: "2026", value: 0 },
    ],
    actions: ["2027년 일정 모니터링", "중동 파트너 리스트 사전 확보", "대체 행사 검토"],
    companies: [
      { name: "OKX", tags: ["Exchange", "Sponsor"], people: ["Institutional Lead"], role: "유동성", layer: "CEX", tgeDone: true, tgeNote: "OKB 토큰" },
      { name: "Animoca Brands", tags: ["Gaming", "Investor"], people: ["Portfolio Lead"], role: "포트폴리오 접근", layer: "VC", tgeDone: true, tgeNote: "다수 포트폴리오 TGE 완료" },
      { name: "Cypher Capital", tags: ["VC", "MENA"], people: ["Managing Partner"], role: "지역 전략", layer: "VC", tgeDone: true, tgeNote: "펀드 자본" },
      { name: "Chainalysis", tags: ["Compliance", "Data"], people: ["Policy Lead"], role: "규제 시그널", layer: "Infra", tgeDone: true, tgeNote: "비토큰 기업" },
    ],
    sideEvents: {
      count: 186,
      label: "사이드 이벤트",
      items: [
        { name: "Dubai DeFi Summit", host: "OKX", date: "2026-04-29", desc: "DeFi 인프라 및 유동성 포럼" },
        { name: "MENA Web3 Connect", host: "Cypher Capital", date: "2026-04-30", desc: "중동 Web3 생태계 네트워킹" },
        { name: "On-chain Compliance Workshop", host: "Chainalysis", date: "2026-04-29", desc: "온체인 규제 및 컴플라이언스" },
      ],
    },
  },
  {
    id: "consensus-miami",
    name: "Consensus Miami",
    city: "Miami",
    country: "United States",
    date: "2026-05-05",
    endDate: "2026-05-07",
    days: 3,
    venue: "Miami Beach Convention Center",
    tier: "S",
    autoTier: "S",
    tierScore: 93,
    tierReasons: ["CoinDesk 주최 플래그십", "20,000+ 참석자 예상", "100+ 국가 참여"],
    gradient: "from-sky-100 via-white to-blue-100",
    status: "completed",
    imageUrl: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/ConsensusMiami2026?k=c",
    website: "https://consensus.coindesk.com/",
    cost: { flight: 1100, hotel: 1500, transport: 180, meals: 420, ticket: 999, total: 4199, note: "Pro Pass 기준" },
    summary: {
      features: ["CoinDesk 주최 북미 최대 크립토 컨퍼런스", "크립토·금융·테크·정책 리더 20,000+ 집결", "마이애미 비치 컨벤션 센터", "Morgan Stanley, JPMorgan 첫 스폰서 참여"],
      difference: ["AI 에이전트 상거래(Agentic Commerce) 트랙 신설 — 브레이크아웃 테마", "기관 참석자 35%로 사상 최고 — 전통 금융 대거 합류", "CFTC 의장 Michael Selig, 상원의원 Ashley Moody 첫 참석"],
      pros: ["미주 최대 규모 크립토 집회", "투자 유치, BD, 정책 네트워킹 기회 풍부", "다양한 트랙으로 포괄적 시야 확보", "Solana Accelerate 3,000+ 빌더 참여"],
      risks: ["프리미엄 패스 가격 높음", "마이애미 호텔 예약 경쟁 치열", "행사 규모가 커서 타겟팅 어려울 수 있음"],
      expectations: ["기관 채택 동향 파악", "AI+크립토 교차 분야 탐색", "규제/정책 업데이트"],
    },
    feed: [
      { label: "행사 종료 — 2027년은 5/4-6 마이애미", time: "2026-05-07", type: "완료" },
      { label: "Morgan Stanley·JPMorgan 첫 스폰서 참여 — 기관 진입 가속", time: "2026-05-06", type: "기관" },
      { label: "CFTC 의장 Michael Selig 첫 참석", time: "2026-05-05", type: "규제" },
      { label: "Agentic Commerce 트랙 브레이크아웃 테마로 부상", time: "2026-05-05", type: "AI" },
      { label: "Solana Accelerate 3,000+ 빌더 참여", time: "2026-05-06", type: "생태계" },
    ],
    archive: {
      year: "2026",
      attendees: "20,000+",
      sideEvents: 500,
      sponsors: 250,
      media: 180,
      eventTitle: "Consensus Miami 2026",
      notes: ["100개국 20,000+ 참석, 200+ Fortune 500 기업 대표 참여", "기관 참석자 35% — Morgan Stanley, JPMorgan 첫 스폰서", "AI·Agentic Commerce, 스테이블코인, RWA 토큰화가 핵심 테마", "500+ 사이드 이벤트, 500+ 연사, 6스테이지 3서밋"],
    },
    kpis: [
      { label: "미팅 적합도", value: "매우 높음", detail: "전 분야" },
      { label: "아카이브 성장", value: "+35%", detail: "참석자 YoY" },
      { label: "기관 비율", value: "35%", detail: "참석자 중 기관" },
    ],
    budget: [
      { label: "항공권", value: 1100 },
      { label: "숙박", value: 1500 },
      { label: "티켓", value: 999 },
      { label: "현지비", value: 600 },
    ],
    sideEventTrend: [
      { label: "2023", value: 160 },
      { label: "2024", value: 210 },
      { label: "2025", value: 250 },
      { label: "2026", value: 500 },
    ],
    actions: ["행사 종료 — 주요 미팅 결과 정리", "2027 Consensus Miami (5/4-6) 일정 확인", "기관 파트너십 후속 미팅 진행"],
    companies: [
      { name: "0G (Zero Gravity)", tags: ["L1", "AI", "DA"], people: ["Team"], role: "⭐ AI 네이티브 L1 — 밸리데이터 모집 중 (Newton Testnet v2)", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터/스토리지 노드 모집" },
      { name: "GenLayer", tags: ["L1", "AI", "LLM Consensus"], people: ["Team"], role: "⭐ LLM 기반 컨센서스 L1 — 인센티브 테스트넷", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 모집 (Asimov/Bradbury Testnet)" },
      { name: "Monad", tags: ["L1", "Parallel EVM"], people: ["Keone Hon (CEO)", "BD Lead"], role: "병렬 EVM L1", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 예정 2026 H2, 아직 메인넷 전" },
      { name: "Sui", tags: ["L1", "Move"], people: ["Evan Cheng (Co-founder)", "Ecosystem Lead"], role: "Move 기반 L1", isNew: true, layer: "L1", tgeDone: true, tgeNote: "SUI 토큰 이미 상장" },
      { name: "Aptos", tags: ["L1", "Move"], people: ["Avery Ching (CTO)", "Partnership Lead"], role: "Move 기반 L1", layer: "L1", tgeDone: true, tgeNote: "APT 토큰 이미 상장" },
      { name: "Sei", tags: ["L1", "Trading"], people: ["Jay Jog (Co-founder)", "BD Lead"], role: "트레이딩 특화 L1", isNew: true, layer: "L1", tgeDone: true, tgeNote: "SEI 토큰 이미 상장" },
      { name: "Berachain", tags: ["L1", "Proof of Liquidity"], people: ["Smokey the Bera (Co-founder)", "Ecosystem Lead"], role: "PoL 기반 L1", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 2026 예상, 아직 메인넷 전" },
      { name: "Celestia", tags: ["L1", "Modular DA"], people: ["Mustafa Al-Bassam (Co-founder)", "Research Lead"], role: "모듈러 DA 레이어", layer: "L1", tgeDone: true, tgeNote: "TIA 토큰 이미 상장" },
      { name: "Coinbase", tags: ["Exchange", "Institutional"], people: ["Institutional Head"], role: "유동성/수탁", layer: "CEX", tgeDone: true, tgeNote: "상장 기업" },
      { name: "Morgan Stanley", tags: ["Finance", "Institutional"], people: ["Digital Assets Lead"], role: "첫 크립토 컨퍼런스 스폰서", isNew: true, layer: "TradFi", tgeDone: true, tgeNote: "상장 기업, 첫 크립토 스폰서" },
      { name: "JPMorgan", tags: ["Finance", "Institutional"], people: ["Blockchain Lead"], role: "첫 크립토 컨퍼런스 스폰서", isNew: true, layer: "TradFi", tgeDone: true, tgeNote: "상장 기업, 첫 크립토 스폰서" },
      { name: "a16z crypto", tags: ["VC", "Research"], people: ["Investment Partner"], role: "시장 리서치", layer: "VC", tgeDone: true, tgeNote: "펀드 자본" },
      { name: "Circle", tags: ["Stablecoin", "Payments"], people: ["Policy Lead"], role: "스테이블코인 규제", layer: "Stablecoin", tgeDone: true, tgeNote: "USDC 발행" },
      { name: "Paradigm", tags: ["VC", "DeFi"], people: ["Research Partner"], role: "DeFi 전략", layer: "VC", tgeDone: true, tgeNote: "펀드 자본" },
    ],
    sideEvents: {
      count: 500,
      label: "사이드 이벤트 (공식 기준)",
      items: [
        { name: "Brunch & Beats with Ashbury at Consensus 2026", host: "Ashbury Legal", date: "2026-05-06", desc: "1 Hotel South Beach — 549+ RSVP (Luma ConsensusMiami2026)", url: "https://luma.com/ConsensusMiami2026?k=c" },
        { name: "Liquid Assets Happy Hour | Cocktails & Convo at RWA House", host: "Victoria Mariscal & Drew/Figure", date: "2026-05-06", desc: "RWA House 칵테일 네트워킹 (City Center, 230+ RSVP)" },
        { name: "Stablecoin Sunrise Run Club", host: "Borderless.xyz & Kevin Lehtiniitty", date: "2026-05-06", desc: "The Shelborne By Proper — 190+ RSVP" },
        { name: "Payments by the Beach | Happy Hour by Omninal", host: "Omninal", date: "2026-05-06", desc: "South Beach — 184+ RSVP" },
        { name: "Money Movement, Rewritten: A Private Stablecoin Reception", host: "Stablecoin Host", date: "2026-05-06", desc: "South Beach — 112+ RSVP, 프라이빗 스테이블코인 리셉션" },
        { name: "EASYCON Miami: GM Reps", host: "CoinEasy", date: "2026-05-06", desc: "Muscle Beach South Beach — 106+ RSVP" },
        { name: "Institutional Onchain: RWAs & Stablecoins", host: "Institutional Host", date: "2026-05-07", desc: "Miami — RWA 및 스테이블코인 기관 포럼" },
        { name: "South of Consensus — Miami 2026", host: "PlaceholderMM", date: "2026-05-07", desc: "Mid-Beach — 토큰 창립자 프라이빗 이브닝 (Waitlist)" },
      ],
    },
  },
  {
    id: "daf-abu-dhabi",
    name: "Digital Assets Forum",
    city: "London",
    country: "United Kingdom",
    date: "2026-02-05",
    endDate: "2026-02-06",
    days: 2,
    venue: "London (상세 장소 TBA)",
    tier: "A",
    autoTier: "A",
    tierScore: 80,
    tierReasons: ["$15조 AUM 기관 모임", "700+ 시니어 참가자", "전용 프라이빗 포럼"],
    gradient: "from-emerald-100 via-white to-teal-100",
    status: "completed",
    imageUrl: "https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=600&h=300&fit=crop",
    website: "https://digitalassetsforum.com/",
    cost: { flight: 780, hotel: 640, transport: 140, meals: 280, ticket: 1200, total: 3040, note: "기관용 초대장 기준. 일반 참가 어려울 수 있음" },
    summary: {
      features: ["자산운용사, 은행, 규제기관이 모이는 프라이빗 포럼", "$15조 이상 AUM 대표 참석", "의도적으로 소규모·고밀도 구성"],
      difference: ["전시/엑스포 없이 순수 기관 중심", "결정권자가 한자리에 모이는 구조", "자본 대화에 최적화"],
      pros: ["높은 품질의 1:1 미팅 보장", "실제 자본 배분 논의 가능", "중동/글로벌 기관 네트워크 접근"],
      risks: ["초대장 전용 - 접근성 제한", "1일 일정으로 타이트", "중동 지정학적 리스크"],
      expectations: ["기관 자본 파트너십 논의", "중동 규제 환경 이해", "토큰화 자산 기회 탐색"],
    },
    feed: [
      { label: "참가자 명단 업데이트", time: "1주 전", type: "참가자" },
      { label: "아부다비 비자 정보 안내", time: "2주 전", type: "여행" },
      { label: "포럼 아젠다 확정", time: "3주 전", type: "아젠다" },
    ],
    archive: {
      year: "2025",
      attendees: "700+",
      sideEvents: 15,
      sponsors: 42,
      media: 28,
      eventTitle: "Digital Assets Forum Abu Dhabi 2025",
      notes: ["소규모 기관 포럼 — 자본 대화에 최적화", "토큰화, 규제 프레임워크에 집중", "$15조+ AUM 대표 참석"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "기관 자본" },
      { label: "아카이브 성장", value: "+15%", detail: "AUM 대표 YoY" },
      { label: "업데이트 주기", value: "3일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 780 },
      { label: "숙박", value: 640 },
      { label: "티켓", value: 1200 },
      { label: "현지비", value: 420 },
    ],
    sideEventTrend: [
      { label: "2023", value: 8 },
      { label: "2024", value: 12 },
      { label: "2025", value: 15 },
      { label: "2026", value: 15 },
    ],
    actions: ["초대장 수령 여부 확인", "기관 타겟 리스트 사전 공유", "중동 규제 브리핑 준비"],
    companies: [
      { name: "ADGM", tags: ["Regulator", "Abu Dhabi"], people: ["CEO"], role: "규제 프레임워크", isNew: true, layer: "Regulator", tgeDone: true, tgeNote: "규제기관" },
      { name: "BlackRock Digital", tags: ["Asset Manager"], people: ["Digital Assets Head"], role: "기관 자본", layer: "TradFi", tgeDone: true, tgeNote: "BUIDL 펀드 운용" },
      { name: "FalconX", tags: ["Broker", "Institutional"], people: ["Institutional Sales"], role: "유동성", layer: "Broker", tgeDone: true, tgeNote: "비토큰 기업" },
      { name: "Mubadala", tags: ["Sovereign Fund"], people: ["Tech Investment Lead"], role: "국부펀드 파트너십", layer: "Sovereign Fund", tgeDone: true, tgeNote: "국부펀드" },
    ],
    sideEvents: {
      count: 15,
      label: "사이드 이벤트",
      items: [
        { name: "ADGM RegTech Forum", host: "ADGM", date: "2026-05-13", desc: "중동 디지털 자산 규제 포럼" },
        { name: "Institutional DeFi Roundtable", host: "BlackRock + FalconX", date: "2026-05-13", desc: "기관 DeFi 채택 라운드테이블" },
      ],
    },
  },
  {
    id: "crypto-valley-2026",
    name: "Crypto Valley Conference",
    city: "Rotkreuz",
    country: "Switzerland",
    date: "2026-05-28",
    endDate: "2026-05-29",
    days: 2,
    venue: "Rotkreuz, Switzerland",
    tier: "B",
    autoTier: "B",
    tierScore: 72,
    tierReasons: ["스위스 크립토 밸리 기반", "기술 중심 고밀도", "프로토콜 엔지니어 집중"],
    gradient: "from-red-100 via-white to-neutral-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/CVC26",
    website: "https://cryptovalleyconference.com/",
    cost: { flight: 850, hotel: 920, transport: 160, meals: 380, ticket: 499, total: 2809 },
    summary: {
      features: ["스위스 '크립토 밸리' 기반 기술 컨퍼런스", "프로토콜 엔지니어, 연구자, 규제자 집중", "심층 기술 대화 중심"],
      difference: ["홍보보다 기술 심도에 집중", "소규모·고품질 참가자", "학술+실무 혼합"],
      pros: ["실제 프로덕션급 시스템 구축자들과 대화", "스위스 규제 환경 이해 기회", "조용하고 집중적인 네트워킹"],
      risks: ["규모가 작아 BD 기회 제한적", "숙박 옵션이 제한적일 수 있음", "다른 S/A급 행사 대비 시그널 밀도 낮음"],
      expectations: ["프로토콜 레벨 기술 논의", "규제/컴플라이언스 인사이트", "유럽 시장 진출 참고"],
    },
    feed: [
      { label: "CFP(발표 제안) 마감 임박", time: "2주 전", type: "아젠다" },
      { label: "숙박 할인 코드 공개", time: "3주 전", type: "비용" },
      { label: "연사 라인업 1차 발표", time: "1개월 전", type: "연사" },
    ],
    archive: {
      year: "2025",
      attendees: "500+",
      sideEvents: 12,
      sponsors: 35,
      media: 18,
      eventTitle: "Crypto Valley Conference 2025",
      notes: ["기술 심도가 높은 소규모 컨퍼런스", "인터오퍼러빌리티, 토큰화, 규제가 주요 주제"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "기술/규제" },
      { label: "아카이브 성장", value: "+8%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "7일", detail: "30일 이상" },
    ],
    budget: [
      { label: "항공권", value: 850 },
      { label: "숙박", value: 920 },
      { label: "티켓", value: 499 },
      { label: "현지비", value: 540 },
    ],
    sideEventTrend: [
      { label: "2023", value: 8 },
      { label: "2024", value: 10 },
      { label: "2025", value: 12 },
      { label: "2026", value: 15 },
    ],
    actions: ["기술 트랙 세션 리뷰", "스위스 규제 업데이트 확인", "유럽 파트너 사전 컨택"],
    companies: [
      { name: "Ethereum Foundation", tags: ["Protocol", "Research"], people: ["Researcher"], role: "프로토콜 개발", layer: "L1", tgeDone: true, tgeNote: "ETH" },
      { name: "Sygnum Bank", tags: ["Banking", "Crypto"], people: ["Digital Assets Lead"], role: "기관 은행", layer: "Banking", tgeDone: true, tgeNote: "비토큰 기업" },
      { name: "SEBA Bank", tags: ["Banking", "Custody"], people: ["Custody Head"], role: "수탁 솔루션", layer: "Banking", tgeDone: true, tgeNote: "비토큰 기업" },
      { name: "Zug Cantonal Office", tags: ["Regulator"], people: ["Digital Policy Lead"], role: "규제 인사이트", layer: "Regulator", tgeDone: true, tgeNote: "규제기관" },
    ],
    sideEvents: {
      count: 15,
      label: "사이드 이벤트",
      items: [
        { name: "CVC Sunset Boat Cruise", host: "Crypto Valley Association", date: "2026-05-28", desc: "전통적인 Lake Zug 선셋 보트 크루즈 — 네트워킹 하이라이트" },
        { name: "VIP Dinner at Villa Villette", host: "CVA", date: "2026-05-28", desc: "초대자 한정 VIP 디너 — 스위스 규제·기관 스테이크홀더" },
        { name: "Interop Workshop", host: "Ethereum Foundation", date: "2026-05-29", desc: "인터오퍼러빌리티 기술 워크숍" },
        { name: "Swiss Crypto Regulation Briefing", host: "Zug Cantonal Office", date: "2026-05-29", desc: "스위스 크립토 규제 업데이트 — Swiss National Bank 참여" },
        { name: "Masterclass: Tokenization & RWA", host: "Lucerne University", date: "2026-05-28", desc: "실물 자산 토큰화 마스터클래스" },
      ],
    },
  },
  {
    id: "buidl-asia-2026",
    name: "BUIDL Asia 2026",
    city: "Seoul",
    country: "South Korea",
    date: "2026-04-16",
    endDate: "2026-04-17",
    days: 2,
    venue: "SOFITEL Ambassador Seoul Hotel",
    tier: "A",
    autoTier: "A",
    tierScore: 82,
    tierReasons: ["한국 대표 기술 컨퍼런스", "KryptoPlanet 주최", "빌더·엔지니어 중심 고밀도"],
    gradient: "from-violet-100 via-white to-pink-100",
    status: "completed",
    isDomestic: true,
    imageUrl: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&h=300&fit=crop",
    website: "https://buidl.asia/",
    cost: { flight: 0, hotel: 0, transport: 50, meals: 80, ticket: 200, total: 330, note: "국내 행사. 항공/숙박 불필요" },
    summary: {
      features: ["한국 크립토 생태계 대표 기술 컨퍼런스", "KryptoPlanet 주최, 다양한 생태계 빌더 집결", "기술 및 비즈니스 개발 심층 공유"],
      difference: ["홍보보다 기술 심도에 집중", "다양한 프로토콜의 빌더들이 한자리에", "실무자 중심 구성"],
      pros: ["국내 최고 수준의 크립토 기술 컨퍼런스", "한국 빌더 생태계 파악 기회", "해외 프로젝트의 한국 진출 교두보"],
      risks: ["규모가 S급 대비 작음", "해외 참석자 비율 제한적"],
      expectations: ["한국 크립토 기술 트렌드 파악", "빌더 네트워킹", "신규 프로젝트 발굴"],
    },
    feed: [
      { label: "행사 성료", time: "2026-04-17", type: "완료" },
      { label: "Illia Polosukhin(Near) 기조연설", time: "2026-04-16", type: "연사" },
      { label: "Sofitel Seoul에서 개최", time: "2026-04-15", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "1,000+",
      sideEvents: 8,
      sponsors: 30,
      media: 15,
      eventTitle: "BUIDL Asia 2025",
      notes: ["기술 중심 컨퍼런스로 한국 Web3 빌더 생태계 집약", "다양한 프로토콜 빌더 참여"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "빌더/기술" },
      { label: "국내 행사", value: "✓", detail: "서울" },
      { label: "상태", value: "종료", detail: "4/16-17" },
    ],
    budget: [
      { label: "항공권", value: 0 },
      { label: "숙박", value: 0 },
      { label: "티켓", value: 200 },
      { label: "현지비", value: 130 },
    ],
    sideEventTrend: [
      { label: "2024", value: 5 },
      { label: "2025", value: 7 },
      { label: "2026", value: 8 },
    ],
    actions: ["행사 종료 — 참관 결과 정리", "만난 빌더 후속 미팅", "내년 일정 모니터링"],
    companies: [
      { name: "OpenGradient", tags: ["L1", "AI", "On-chain ML"], people: ["Team"], role: "⭐ 온체인 AI/ML L1 — 밸리데이터 모집 중", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 필요" },
      { name: "Kite AI", tags: ["L1", "AI", "Proof of AI"], people: ["Team"], role: "⭐ AI 인프라 L1 — 밸리데이터 모집 중", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 필요" },
      { name: "KryptoPlanet", tags: ["Organizer", "Korea"], people: ["Organizer"], role: "주최사", layer: "Organizer", tgeDone: false, tgeNote: "행사 주최" },
      { name: "NEAR Protocol", tags: ["L1", "AI"], people: ["Illia Polosukhin (CEO)"], role: "기조연설", isNew: true, layer: "L1", tgeDone: true, tgeNote: "NEAR 토큰" },
      { name: "EigenLayer", tags: ["Restaking", "Infra"], people: ["Developer Relations"], role: "기술 발표", layer: "Infra", tgeDone: true, tgeNote: "EIGEN 토큰" },
      { name: "Story Protocol", tags: ["IP", "L1"], people: ["BD Lead"], role: "IP 인프라", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 예정" },
    ],
    sideEvents: {
      count: 5,
      label: "사이드 이벤트",
      items: [
        { name: "BuidlHack 2026 Builder Day", host: "KBWA + BNB Chain + Near AI", date: "2026-04-14", desc: "총상금 $26,000 규모 글로벌 해커톤 빌더 데이" },
        { name: "AI & Infrastructure Conference", host: "KBWA", date: "2026-04-15", desc: "Korea Buidl Week 내 AI·인프라 컨퍼런스" },
        { name: "Finance Summit", host: "KBWA", date: "2026-04-15", desc: "금융·디지털자산 관련 서밋 프로그램" },
        { name: "CIS 2026", host: "KBWA", date: "2026-04-17", desc: "BUIDL Asia 이후 4/17-19 진행되는 연계 프로그램" },
        { name: "BuidlHack Final Presentations", host: "KBWA", date: "2026-04-18", desc: "해커톤 최종 발표 및 빌더 쇼케이스" },
      ],
    },
  },
  {
    id: "istanbul-blockchain-week-2026",
    name: "Istanbul Blockchain Week 2026",
    city: "Istanbul",
    country: "Turkey",
    date: "2026-06-02",
    endDate: "2026-06-03",
    days: 2,
    venue: "Hilton Bomonti Hotel",
    tier: "B",
    autoTier: "B",
    tierScore: 70,
    tierReasons: ["터키 대표 블록체인 주간", "EAK Digital 주최 5회차", "유럽-아시아 교차 허브"],
    gradient: "from-teal-100 via-white to-cyan-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&h=300&fit=crop",
    website: "https://istanbulblockchainweek.com/",
    cost: { flight: 650, hotel: 580, transport: 120, meals: 200, ticket: 399, total: 1949 },
    summary: {
      features: ["터키·이스탄불에서 열리는 연례 블록체인 주간", "EAK Digital 주최, 5회차", "유럽과 아시아를 잇는 크립토 허브"],
      difference: ["터키 시장 직접 접근", "동유럽·중동 크립토 커뮤니티 포커스", "비교적 저비용 참여 가능"],
      pros: ["터키 크립토 채택률 세계 최상위", "이스탄불 지리적 이점", "비용 효율적"],
      risks: ["규모가 S/A급 대비 작음", "터키 경제 변동성", "영어 외 언어 장벽 가능"],
      expectations: ["터키/중동 시장 파트너십", "지역 규제 동향 파악", "신흥 시장 인사이트"],
    },
    feed: [
      { label: "얼리버드 티켓 판매 중", time: "2주 전", type: "비용" },
      { label: "스피커 모집 오픈", time: "1개월 전", type: "연사" },
      { label: "Hilton Bomonti 장소 확정", time: "2개월 전", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "3,000+",
      sideEvents: 25,
      sponsors: 45,
      media: 20,
      eventTitle: "Istanbul Blockchain Week 2025",
      notes: ["터키 최대 블록체인 행사", "지역 채택, DeFi, Web3 게임에 집중"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "지역/신흥" },
      { label: "아카이브 성장", value: "+12%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "60일 이내" },
    ],
    budget: [
      { label: "항공권", value: 650 },
      { label: "숙박", value: 580 },
      { label: "티켓", value: 399 },
      { label: "현지비", value: 320 },
    ],
    sideEventTrend: [
      { label: "2024", value: 20 },
      { label: "2025", value: 25 },
      { label: "2026", value: 4 },
    ],
    actions: ["얼리버드 등록", "터키 시장 타겟 리스트 작성", "현지 파트너 사전 컨택"],
    companies: [
      { name: "EAK Digital", tags: ["Organizer", "Marketing"], people: ["CEO"], role: "주최사", layer: "Organizer", tgeDone: true, tgeNote: "에이전시" },
      { name: "BtcTurk", tags: ["Exchange", "Turkey"], people: ["CEO"], role: "거래소", layer: "CEX", tgeDone: true, tgeNote: "터키 최대 거래소" },
      { name: "Paribu", tags: ["Exchange", "Turkey"], people: ["BD Lead"], role: "거래소", layer: "CEX", tgeDone: true, tgeNote: "터키 주요 거래소" },
      { name: "Avalanche", tags: ["L1", "Subnet"], people: ["Ecosystem Lead"], role: "L1 파트너십", layer: "L1", tgeDone: true, tgeNote: "AVAX 토큰" },
    ],
    sideEvents: {
      count: 4,
      label: "사이드 이벤트",
      items: [
        { name: "Istanbul Institutional Markets Summit", host: "Istanbul Blockchain Week", date: "2026-06-02", desc: "정책입안자·규제기관·금융기관 대상 폐쇄형 기관 포럼" },
        { name: "Blockdown Music Festival", host: "Blockdown + IBW", date: "2026-06-02", desc: "이스탄불 대표 음악 베뉴에서 열리는 Web3 음악·문화 파티" },
        { name: "KOL Meet-and-Greets", host: "Istanbul Blockchain Week", date: "2026-06-03", desc: "글로벌 Web3 KOL과의 네트워킹·미디어 라운지 프로그램" },
        { name: "Main Summit Networking Lounge", host: "Istanbul Blockchain Week", date: "2026-06-02", desc: "전시·키노트·패널과 연결되는 공식 네트워킹 라운지" },
      ],
    },
  },
  {
    id: "blockchain-futurist-2026",
    name: "Blockchain Futurist Conference 2026",
    city: "Toronto",
    country: "Canada",
    date: "2026-07-21",
    endDate: "2026-07-22",
    days: 2,
    venue: "Rebel & Cabana, Toronto",
    tier: "B",
    autoTier: "B",
    tierScore: 71,
    tierReasons: ["캐나다 최대 Web3 행사", "9회차 연례 컨퍼런스", "Rebel & Cabana 대형 베뉴"],
    gradient: "from-indigo-100 via-white to-purple-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1517935706615-2717063c2225?w=600&h=300&fit=crop",
    website: "https://futuristconference.com/",
    cost: { flight: 950, hotel: 880, transport: 150, meals: 350, ticket: 599, total: 2929 },
    summary: {
      features: ["캐나다 최대 규모 Web3·크립토 행사", "9회차를 맞이하는 캐나다 홈커밍 에디션", "Rebel & Cabana 야외/실내 복합 베뉴"],
      difference: ["캐나다 규제·정책 포커스", "북미 시장 진출 교두보", "ETH/DeFi 커뮤니티 강세"],
      pros: ["캐나다 크립토 허브 직접 경험", "비교적 저렴한 참가비", "북미 파트너십 기회"],
      risks: ["S급 행사 대비 글로벌 영향력 제한", "토론토 여름 호텔 경쟁", "캐나다 규제 불확실성"],
      expectations: ["캐나다 Web3 생태계 파악", "북미 파트너십 탐색", "규제·정책 인사이트"],
    },
    feed: [
      { label: "CFP(발표 제안) 오픈", time: "1개월 전", type: "아젠다" },
      { label: "얼리버드 티켓 25% 할인", time: "3주 전", type: "비용" },
      { label: "Rebel & Cabana 베뉴 확정", time: "2개월 전", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "5,000+",
      sideEvents: 35,
      sponsors: 60,
      media: 30,
      eventTitle: "Blockchain Futurist Conference 2025",
      notes: ["캐나다 Web3 핵심 행사", "ETH 커뮤니티, DeFi, 규제에 집중"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "북미/DeFi" },
      { label: "아카이브 성장", value: "+10%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "60일 이내" },
    ],
    budget: [
      { label: "항공권", value: 950 },
      { label: "숙박", value: 880 },
      { label: "티켓", value: 599 },
      { label: "현지비", value: 500 },
    ],
    sideEventTrend: [
      { label: "2024", value: 28 },
      { label: "2025", value: 35 },
      { label: "2026", value: 16 },
    ],
    actions: ["얼리버드 25% 할인 등록", "캐나다 규제 브리핑 준비", "북미 타겟 파트너 사전 리스트"],
    companies: [
      { name: "Ethereum Foundation", tags: ["Protocol", "Research"], people: ["Researcher"], role: "프로토콜", layer: "L1", tgeDone: true, tgeNote: "ETH" },
      { name: "ChainSafe", tags: ["Infra", "Canada"], people: ["CEO"], role: "인프라", layer: "Infra", tgeDone: true, tgeNote: "캐나다 기반" },
      { name: "Coinsquare", tags: ["Exchange", "Canada"], people: ["Institutional Lead"], role: "거래소", layer: "CEX", tgeDone: true, tgeNote: "캐나다 규제 거래소" },
      { name: "DFINITY", tags: ["L1", "ICP"], people: ["Ecosystem Lead"], role: "L1 파트너십", layer: "L1", tgeDone: true, tgeNote: "ICP 토큰" },
    ],
    sideEvents: {
      count: 16,
      label: "사이드 이벤트 (Luma Canada Crypto Week 기준)",
      items: [
        { name: "Blockchain Futurist Conference", host: "Blockchain Futurist Conference Week", date: "2026-07-21", desc: "메인 컨퍼런스 (Rebel, CA$299) — Canada Crypto Week 핵심" },
        { name: "ETHToronto 2026", host: "Canada Crypto Week", date: "2026-07-22", desc: "Rebel — 이더리움 커뮤니티 토론토 에디션" },
        { name: "ETHWomen Toronto 2026", host: "Canada Crypto Week", date: "2026-07-22", desc: "Rebel — 여성 이더리움 커뮤니티 이벤트" },
        { name: "AI Futurist Conference", host: "Canada Crypto Week", date: "2026-07-22", desc: "Rebel — AI 컨퍼런스" },
        { name: "Bored Club Canada @ BFC", host: "Canada Crypto Week", date: "2026-07-21", desc: "Rebel — Bored Ape 커뮤니티 모임" },
        { name: "Pudgy Penguins Canada @ BFC", host: "Canada Crypto Week", date: "2026-07-21", desc: "Rebel — Pudgy Penguins 커뮤니티 모임" },
        { name: "Crypto, Web3 & AI Bootcamp for Beginners", host: "Canada Crypto Week", date: "2026-07-21", desc: "Rebel — 초보자 대상 크립토/Web3/AI 부트캠프" },
        { name: "Shefi Morning Social @ BFC", host: "Blockchain Futurist Conference Week & Lalla", date: "2026-07-21", desc: "Rebel — Shefi 커뮤니티 모닝 소셜" },
      ],
    },
  },
  {
    id: "bitcoin-asia-2026",
    name: "Bitcoin Asia 2026",
    city: "Hong Kong",
    country: "China (Hong Kong)",
    date: "2026-08-27",
    endDate: "2026-08-28",
    days: 2,
    venue: "Hong Kong Convention Center",
    tier: "S",
    autoTier: "S",
    tierScore: 88,
    tierReasons: ["아시아 최대 비트코인 이벤트", "Bitcoin Conference 공식 아시아 에디션", "홍콩 컨벤션 센터"],
    gradient: "from-rose-100 via-white to-orange-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/bitcoin-asia?k=c",
    website: "https://b.tc/conference/asia",
    cost: { flight: 450, hotel: 920, transport: 100, meals: 250, ticket: 58, total: 1778, note: "General Admission 기준. GA Plus는 $107, Whale Pass는 $2,688" },
    summary: {
      features: ["Bitcoin Conference 공식 아시아 에디션", "아시아 최대 규모 비트코인 집회", "홍콩 컨벤션 센터 2일 행사"],
      difference: ["아시아 시장 직접 접근", "비트코인 단일 자산 심층 집중", "홍콩 웹3 허브 위치"],
      pros: ["아시아 비트코인 생태계 원스톱 파악", "홍콩 규제·금융 허브 인사이트", "비교적 저렴한 항공권"],
      risks: ["비트코인 외 프로토콜 관련성 제한", "홍콩 정치·규제 불확실성", "여름날씨(고온다습)"],
      expectations: ["아시아 비트코인 채택 동향", "홍콩 금융 허브 파트너십", "채굴·에너지 인프라 논의"],
    },
    feed: [
      { label: "GA 티켓 $58 판매 중", time: "현재", type: "비용" },
      { label: "아시아 최대 비트코인 디지털 아트 전시", time: "2주 전", type: "프로그램" },
      { label: "홍콩 컨벤션 센터 장소 확정", time: "1개월 전", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "8,000+",
      sideEvents: 60,
      sponsors: 80,
      media: 45,
      eventTitle: "Bitcoin Asia 2025",
      notes: ["아시아 첫 Bitcoin Conference", "아시아 채택, 규제, 채굴에 집중", "홍콩 컨벤션 센터 개최"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "BTC/아시아" },
      { label: "아카이브 성장", value: "+30%", detail: "아시아 첫 에디션" },
      { label: "업데이트 주기", value: "7일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 450 },
      { label: "숙박", value: 920 },
      { label: "티켓", value: 58 },
      { label: "현지비", value: 350 },
    ],
    sideEventTrend: [
      { label: "2024", value: 0 },
      { label: "2025", value: 60 },
      { label: "2026", value: 3 },
    ],
    actions: ["GA 티켓 조기 구매", "아시아 파트너 사전 리스트", "홍콩 숙박 조기 예약"],
    companies: [
      { name: "Bitcoin Magazine", tags: ["Organizer", "Media"], people: ["CEO"], role: "주최사", layer: "Organizer", tgeDone: true, tgeNote: "Bitcoin Conference 시리즈 주최" },
      { name: "HashKey Group", tags: ["Exchange", "Hong Kong"], people: ["CEO"], role: "거래소/규제", layer: "CEX", tgeDone: true, tgeNote: "홍콩 규제 거래소" },
      { name: "OKX", tags: ["Exchange", "Global"], people: ["Institutional Lead"], role: "유동성", layer: "CEX", tgeDone: true, tgeNote: "OKB 토큰" },
      { name: "Lightning Labs", tags: ["Lightning", "Infra"], people: ["CTO"], role: "라이트닝 인프라", layer: "Infra", tgeDone: false, tgeNote: "비트코인 L2" },
    ],
    sideEvents: {
      count: 3,
      label: "사이드 이벤트",
      items: [
        { name: "Whale Night", host: "Bitcoin Asia", date: "2026-08-27", desc: "Whale Pass 포함 VIP 네트워킹 나이트" },
        { name: "Official After Party", host: "Bitcoin Asia", date: "2026-08-28", desc: "스탠드얼론 티켓 제공 공식 애프터파티 — DJ·라이브 엔터테인먼트" },
        { name: "Deal Flow Zone & Networking Lounge", host: "Bitcoin Asia", date: "2026-08-27", desc: "GA Plus 이상 대상 1:1 비즈니스 미팅·네트워킹 공간" },
      ],
    },
  },
  {
    id: "kbw-2026",
    name: "Korea Blockchain Week 2026",
    city: "Seoul",
    country: "South Korea",
    date: "2026-09-29",
    endDate: "2026-10-01",
    days: 3,
    venue: "Walkerhill Hotel & Resort, Seoul",
    tier: "S",
    autoTier: "S",
    tierScore: 89,
    tierReasons: ["아시아 최대 크립토 컨퍼런스", "13,000+ 참석자", "Upbit 메인 스폰서"],
    gradient: "from-blue-100 via-white to-red-100",
    status: "upcoming",
    isDomestic: true,
    imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/korea-blockchain-week?k=c",
    website: "https://koreablockchainweek.com/",
    cost: { flight: 0, hotel: 0, transport: 80, meals: 150, ticket: 300, total: 530, note: "국내 행사. 항공/숙박 불필요" },
    summary: {
      features: ["아시아 최대 규모 블록체인·크립토 위크", "FactBlock 주최, Upbit 메인 스폰서", "9/29 사전 기관 서밋 + 9/30~10/1 메인 컨퍼런스"],
      difference: ["한국 고유의 문화·엔터테인먼트 융합", "K-POP·스포츠·크립토 교차", "아시아 시장 전면 집중"],
      pros: ["국내 최대 행사 — 참가 부담 최소", "13,000+ 글로벌 참석자와 네트워킹", "Arthur Hayes, Jeff Yan(Hyperliquid) 등 연사"],
      risks: ["행사 규모가 커 타겟팅 필요", "국내 규제 불확실성", "9월 말 일정 관리"],
      expectations: ["한국 크립토 시장 트렌드 파악", "글로벌·아시아 파트너십", "Web3·AI·RWA 최신 동향"],
    },
    feed: [
      { label: "Arthur Hayes 기조연설 확정", time: "1주 전", type: "연사" },
      { label: "Upbit 메인 스폰서 발표", time: "2주 전", type: "스폰서" },
      { label: "티켓 판매 시작", time: "1개월 전", type: "비용" },
    ],
    archive: {
      year: "2025",
      attendees: "13,000+",
      sideEvents: 780,
      sponsors: 150,
      media: 80,
      eventTitle: "Korea Blockchain Week 2025",
      notes: ["아시아 최대 크립토 행사", "Web3, AI, RWA, 규제가 핵심 주제", "13,000+ 참석자, 780+ 사이드 이벤트, Arthur Hayes 등 연사"],
    },
    kpis: [
      { label: "미팅 적합도", value: "매우 높음", detail: "아시아/전 분야" },
      { label: "아카이브 성장", value: "+18%", detail: "참석자 YoY" },
      { label: "국내 행사", value: "✓", detail: "서울" },
    ],
    budget: [
      { label: "항공권", value: 0 },
      { label: "숙박", value: 0 },
      { label: "티켓", value: 300 },
      { label: "현지비", value: 230 },
    ],
    sideEventTrend: [
      { label: "2024", value: 95 },
      { label: "2025", value: 780 },
      { label: "2026", value: 1 },
    ],
    actions: ["얼리버드 티켓 구매", "기관 서밋 초대장 확인", "사이드 이벤트 호스팅 검토"],
    companies: [
      { name: "0G (Zero Gravity)", tags: ["L1", "AI", "DA"], people: ["Team"], role: "⭐ AI 네이티브 L1 — 밸리데이터 모집 중", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터/스토리지 노드 모집" },
      { name: "GenLayer", tags: ["L1", "AI", "LLM Consensus"], people: ["Team"], role: "⭐ LLM 기반 컨센서스 L1 — 테스트넷", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 모집" },
      { name: "FactBlock", tags: ["Organizer", "Korea"], people: ["CEO"], role: "주최사", layer: "Organizer", tgeDone: true, tgeNote: "행사 주최" },
      { name: "Upbit (Dunamu)", tags: ["Exchange", "Korea"], people: ["Kyoungsuk Oh (CEO)"], role: "메인 스폰서", isNew: true, layer: "CEX", tgeDone: true, tgeNote: "한국 최대 거래소" },
      { name: "Hyperliquid Labs", tags: ["DeFi", "Perps"], people: ["Jeff Yan (CEO)"], role: "DeFi 인프라", isNew: true, layer: "DeFi", tgeDone: true, tgeNote: "HYPE 토큰" },
      { name: "Maelstrom", tags: ["VC", "Investment"], people: ["Arthur Hayes (CIO)"], role: "투자", layer: "VC", tgeDone: true, tgeNote: "BitMEX 창업자 펀드" },
    ],
    sideEvents: {
      count: 1,
      label: "사이드 이벤트",
      items: [
        { name: "Upbit Institutional Summit", host: "Upbit + FactBlock", date: "2026-09-29", desc: "KBW2026 개막 전 초대자 한정 기관 서밋 — 자본시장·정책·규제 논의" },
      ],
    },
  },
  {
    id: "cis-2026",
    name: "CIS 2026 (Crypto Investment Show)",
    city: "Seoul",
    country: "South Korea",
    date: "2026-04-17",
    endDate: "2026-04-19",
    days: 3,
    venue: "Seoul (상세 TBA)",
    tier: "A",
    autoTier: "A",
    tierScore: 81,
    tierReasons: ["한국 대형 디지털 자산 투자 쇼", "200+ 연사", "50+ 스폰서"],
    gradient: "from-fuchsia-100 via-white to-pink-100",
    status: "completed",
    isDomestic: true,
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=300&fit=crop",
    website: "https://cryptoinvestmentshow.com/",
    cost: { flight: 0, hotel: 0, transport: 60, meals: 100, ticket: 150, total: 310, note: "국내 행사. 항공/숙박 불필요" },
    summary: {
      features: ["한국 대표 디지털 자산 투자 컨퍼런스", "기관 포럼(Day 1) + 리테일 페스티벌(Day 2-3)", "200+ 연사, 50+ 스폰서 참여"],
      difference: ["투자 시각 중심 — 빌더보다 투자자 타겟", "한국 전통 금융×디지털 자산 교차", "BUIDL Asia와 동일 Korea BUIDL Week 일정"],
      pros: ["국내 최대 투자 중심 크립토 행사", "전통 금융(한화투자증권 등) 참여", "일반인 대상 리테일 페스티벌"],
      risks: ["규모가 S급 글로벌 행사 대비 작음", "투자/리테일 중심이라 기술 심도 제한"],
      expectations: ["한국 투자자 시그널 파악", "전통 금융×크립토 교차 인사이트", "리테일 시장 트렌드"],
    },
    feed: [
      { label: "행사 성료", time: "2026-04-19", type: "완료" },
      { label: "기관 포럼 매진", time: "2026-04-17", type: "운영" },
      { label: "한화투자증권 CSO 기조연설", time: "2026-04-17", type: "연사" },
    ],
    archive: {
      year: "2025",
      attendees: "3,000+",
      sideEvents: 10,
      sponsors: 50,
      media: 40,
      eventTitle: "CIS 2025 (Crypto Investment Show)",
      notes: ["Korea BUIDL Week 기간 중 개최", "기관 투자 + 리테일 페스티벌 구성"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "투자/기관" },
      { label: "국내 행사", value: "✓", detail: "서울" },
      { label: "상태", value: "종료", detail: "4/17-19" },
    ],
    budget: [
      { label: "항공권", value: 0 },
      { label: "숙박", value: 0 },
      { label: "티켓", value: 150 },
      { label: "현지비", value: 160 },
    ],
    sideEventTrend: [
      { label: "2024", value: 5 },
      { label: "2025", value: 8 },
      { label: "2026", value: 10 },
    ],
    actions: ["행사 종료 — 참관 결과 정리", "만난 투자자 후속 미팅", "내년 일정 모니터링"],
    companies: [
      { name: "Ault", tags: ["L1", "Korea"], people: ["Team"], role: "⭐ L1 프로토콜 — 밸리데이터 모집 중", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 필요" },
      { name: "Xangle", tags: ["Data", "Korea"], people: ["James Kim (Co-CEO)", "Lihan Lee (Co-CEO)"], role: "데이터 파트너", isNew: true, layer: "Data", tgeDone: true, tgeNote: "한국 크립토 데이터" },
      { name: "Hanwha Investment & Securities", tags: ["TradFi", "Korea"], people: ["Jongmin Son (CSO)"], role: "전통 금융", layer: "TradFi", tgeDone: true, tgeNote: "한국 증권사" },
      { name: "Meritz Securities", tags: ["TradFi", "Korea"], people: ["Byungha Kang (MD)"], role: "전통 금융", layer: "TradFi", tgeDone: true, tgeNote: "한국 증권사" },
      { name: "Bain & Company", tags: ["Consulting", "Global"], people: ["Wooseok Shin (Partner)"], role: "컨설팅", layer: "Consulting", tgeDone: true, tgeNote: "글로벌 컨설팅" },
    ],
    sideEvents: {
      count: 10,
      label: "사이드 이벤트",
      items: [
        { name: "Institutional Forum", host: "CIS", date: "2026-04-17", desc: "기관 투자자 전용 포럼" },
        { name: "Retail Festival", host: "CIS", date: "2026-04-18", desc: "일반 투자자 대상 페스티벌" },
      ],
    },
  },
  {
    id: "hk-web3-festival-2026",
    name: "Hong Kong Web3 Festival 2026",
    city: "Hong Kong",
    country: "China (Hong Kong)",
    date: "2026-04-20",
    endDate: "2026-04-23",
    days: 4,
    venue: "Hong Kong Convention and Exhibition Centre (HKCEC)",
    tier: "S",
    autoTier: "S",
    tierScore: 91,
    tierReasons: ["아시아 최대 Web3 이벤트", "100,000+ 누적 참석자", "Wanxiang+HashKey 공동 주최"],
    gradient: "from-red-100 via-white to-amber-100",
    status: "completed",
    imageUrl: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/hkweb3festival_2026",
    website: "https://www.web3festival.org/",
    cost: { flight: 450, hotel: 1100, transport: 100, meals: 280, ticket: 200, total: 2130, note: "일반 패스 기준" },
    summary: {
      features: ["아시아 최대 규모 Web3 페스티벌 (4회차)", "Wanxiang Blockchain Labs + HashKey Group 공동 주최", "HKCEC 4일간 개최, 350+ 전시부스"],
      difference: ["중국·홍콩 정부 참여가 특징", "전통 금융(BlackRock, HSBC)과 Web3 교차", "규제·정책 중심 대화"],
      pros: ["아시아 Web3 생태계 원스톱", "홍콩 금융 허브 인프라", "블랙록·파테라 등 기관 참여"],
      risks: ["홍콩 정치·규제 리스크", "중국 본토 접근성 제한", "4월 홍콩 날씨(습함)"],
      expectations: ["홍콩 Web3 정책 시그널", "아시아 기관 자본 동향", "ETF·RWA 토큰화 진전"],
    },
    feed: [
      { label: "행사 성료", time: "2026-04-23", type: "완료" },
      { label: "BlackRock·OKX·Solana 연사", time: "2026-04-20", type: "연사" },
      { label: "홍콩 재정국장 개막연설", time: "2026-04-20", type: "기조" },
    ],
    archive: {
      year: "2025",
      attendees: "50,000+",
      sideEvents: 200,
      sponsors: 250,
      media: 150,
      eventTitle: "Hong Kong Web3 Festival 2025",
      notes: ["아시아 최대 Web3 행사", "홍콩 정부, 기관 자본, 중국 생태계 집결", "50,000+ 참석자, 200개 사이드 이벤트"],
    },
    kpis: [
      { label: "미팅 적합도", value: "매우 높음", detail: "아시아/기관" },
      { label: "아카이브 성장", value: "+20%", detail: "참석자 YoY" },
      { label: "상태", value: "종료", detail: "4/20-23" },
    ],
    budget: [
      { label: "항공권", value: 450 },
      { label: "숙박", value: 1100 },
      { label: "티켓", value: 200 },
      { label: "현지비", value: 380 },
    ],
    sideEventTrend: [
      { label: "2023", value: 100 },
      { label: "2024", value: 150 },
      { label: "2025", value: 200 },
      { label: "2026", value: 200 },
    ],
    actions: ["행사 종료 — 참관 결과 정리", "홍콩 파트너 후속", "2027 일정 모니터링"],
    companies: [
      { name: "Wanxiang Blockchain Labs", tags: ["Organizer", "China"], people: ["Xiao Feng (Chairman)"], role: "공동 주최", layer: "Organizer", tgeDone: true, tgeNote: "Wanxiang 블록체인" },
      { name: "HashKey Group", tags: ["Exchange", "Hong Kong"], people: ["Xiao Feng (Chairman)"], role: "공동 주최", layer: "CEX", tgeDone: true, tgeNote: "홍콩 규제 거래소" },
      { name: "BlackRock", tags: ["Asset Manager", "Institutional"], people: ["Abdelhamid Bizid (MD)"], role: "기관 자본", isNew: true, layer: "TradFi", tgeDone: true, tgeNote: "세계 최대 자산운용사" },
      { name: "OKX", tags: ["Exchange", "Global"], people: ["Lennix Lai (CCO)"], role: "유동성", layer: "CEX", tgeDone: true, tgeNote: "OKB 토큰" },
      { name: "Solana Foundation", tags: ["L1", "Global"], people: ["Lily Liu (President)"], role: "L1 생태계", layer: "L1", tgeDone: true, tgeNote: "SOL 토큰" },
      { name: "Animoca Brands", tags: ["Gaming", "VC"], people: ["Yat Siu (Chairman)"], role: "게이밍/VC", layer: "VC", tgeDone: true, tgeNote: "다수 포트폴리오" },
    ],
    sideEvents: {
      count: 200,
      label: "사이드 이벤트",
      items: [
        { name: "HashKey Capital Summit", host: "HashKey Capital", date: "2026-04-21", desc: "기관 투자 서밋" },
        { name: "Solana Breakpoint HK", host: "Solana Foundation", date: "2026-04-22", desc: "솔라나 개발자 모임" },
      ],
    },
  },
  {
    id: "seabw-2026",
    name: "Southeast Asia Blockchain Week 2026",
    city: "Bangkok",
    country: "Thailand",
    date: "2026-05-18",
    endDate: "2026-05-24",
    days: 7,
    venue: "True ICON Hall, ICONSIAM, Bangkok",
    tier: "A",
    autoTier: "A",
    tierScore: 79,
    tierReasons: ["동남아 최대 Web3 컨퍼런스", "규제·기관·AI 테마", "무료 일반 패스"],
    gradient: "from-emerald-100 via-white to-yellow-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&h=300&fit=crop",
    sideEventUrl: "https://www.seablockchainweek.org/side-events",
    sideEventSourceUrl: "https://luma.com/SEABW_Official",
    website: "https://seablockchainweek.com/",
    cost: { flight: 500, hotel: 450, transport: 80, meals: 150, ticket: 0, total: 1180, note: "일반 패스 무료! 항공+숙박만 부담" },
    summary: {
      features: ["동남아시아 최대 Web3·블록체인 위크", "규제·기관·RWA·AI·인프라 5개 트랙", "일반 패스 최초 무료 개방"],
      difference: ["동남아 시장 직접 접근", "태국·인도네시아·베트남 규제 인사이트", "무료 참가로 진입 장벽 없음"],
      pros: ["동남아 신흥 크립토 시장 원스톱", "Hashed·Coinbase·Google 연사", "방콕 저비용"],
      risks: ["S급 행사 대비 글로벌 영향력 제한", "동남아 시장 변동성", "태국 정치 불안정"],
      expectations: ["동남아 규제 프레임워크 파악", "신흥 시장 파트너십", "RWA·AI 트렌드"],
    },
    feed: [
      { label: "일반 패스 무료 오픈", time: "3주 전", type: "비용" },
      { label: "Google·Coinbase 연사 확정", time: "1개월 전", type: "연사" },
      { label: "5개 메인 트랙 발표", time: "2개월 전", type: "아젠다" },
      { label: "Luma 사이드 이벤트 7개 공개 — RSVP 오픈", time: "2026-05-05", type: "사이드 이벤트" },
    ],
    archive: {
      year: "2025",
      attendees: "5,000+",
      sideEvents: 40,
      sponsors: 60,
      media: 25,
      eventTitle: "Southeast Asia Blockchain Week 2025",
      notes: ["동남아 최대 Web3 행사", "규제, 기관, RWA, AI가 핵심 주제", "40개 사이드 이벤트"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "동남아/신흥" },
      { label: "아카이브 성장", value: "+15%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "7일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 500 },
      { label: "숙박", value: 450 },
      { label: "티켓", value: 0 },
      { label: "현지비", value: 230 },
    ],
    sideEventTrend: [
      { label: "2024", value: 30 },
      { label: "2025", value: 40 },
      { label: "2026", value: 7 },
    ],
    actions: ["무료 일반 패스 등록", "동남아 파트너 리스트 작성", "방콕 숙박 조기 예약", "사이드 이벤트 RSVP 마감 전 등록"],
    companies: [
      { name: "0G (Zero Gravity)", tags: ["L1", "AI", "DA"], people: ["Team"], role: "⭐ AI 네이티브 L1 — 밸리데이터 모집 중", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터/스토리지 노드 모집" },
      { name: "GenLayer", tags: ["L1", "AI", "LLM Consensus"], people: ["Team"], role: "⭐ LLM 기반 컨센서스 L1 — 인센티브 테스트넷", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 모집" },
      { name: "Hashed", tags: ["VC", "Korea"], people: ["Simon Kim (CEO)"], role: "한국 VC", isNew: true, layer: "VC", tgeDone: true, tgeNote: "한국 대표 크립토 VC" },
      { name: "Avalanche", tags: ["L1", "Global"], people: ["Justin Kim (Head of Asia)"], role: "L1 파트너십", layer: "L1", tgeDone: true, tgeNote: "AVAX 토큰" },
      { name: "Coinbase", tags: ["Exchange", "Institutional"], people: ["Nicholas See Tong (APAC Lead)"], role: "거래소/APAC", layer: "CEX", tgeDone: true, tgeNote: "상장 기업" },
      { name: "Google", tags: ["Tech", "Cloud"], people: ["Iñaki Moreno Girona (Strategic Partnerships)"], role: "클라우드/인프라", layer: "Tech", tgeDone: true, tgeNote: "비토큰 기업" },
    ],
    sideEvents: {
      count: 16,
      label: "사이드 이벤트",
      items: [
        { name: "AI DEMO DAY: BKK Builders Edition", host: "APE X CRYPTO, OnlyFounders", date: "2026-05-18", desc: "AI 데모 데이 빌더스 에디션 — 426+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "The Alternative Asset Class: RWA Edition", host: "Binance TH Academy", date: "2026-05-18", desc: "RWA 대체 자산 에디션 @Conrad Bangkok — 92+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "ROAD TO SENSUS: BKK EDITION", host: "ContributionDAO", date: "2026-05-18", desc: "SEABW 공식 커뮤니티 이벤트 — 124+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "Bitkub x Block Street: Vision Day", host: "Bitkub", date: "2026-05-19", desc: "Bitkub 주최 비전·네트워킹 데이 @ZillaSpace — 214+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "TOKENISED BANGKOK", host: "UVECON.VC & DTC Group", date: "2026-05-20", desc: "토큰화/RWA 중심 방콕 사이드 이벤트", url: "https://luma.com/SEABW_Official" },
        { name: "SEABW2026 SPEAKER & VIP Night", host: "SEABW Official", date: "2026-05-20", desc: "초대자 한정 VIP 나이트 — Sold Out", url: "https://luma.com/SEABW_Official" },
        { name: "2nd Unofficial Solana and Friends Meetup, Bangkok Edition", host: "OnlyFounders + Superteam Thailand", date: "2026-05-21", desc: "Solana 생태계 비공식 밋업 — 106+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "BUILDERS CAPITAL NIGHT X BLOCK:LOUNGE", host: "9 CAT Group", date: "2026-05-21", desc: "공식 SEABW 2026 사이드 이벤트 @Escape Bangkok", url: "https://luma.com/SEABW_Official" },
        { name: "BINANCE TH Pizza Day 🍕", host: "BINANCE TH", date: "2026-05-22", desc: "바이낸스 TH 피자 데이 @SKYVIEW Hotel — 234+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "RWA × DePIN × Infra: The Bangkok Sessions", host: "Hashcut + Keeping Up With Crypto", date: "2026-05-22", desc: "RWA, DePIN, 인프라 주제 SEABW 사이드 이벤트 — 109+ RSVP", url: "https://luma.com/hwpzdegr" },
        { name: "Bitkub Bitcoin Pizza Day 2026 Powered by Zircuit", host: "Bitkub + Zircuit", date: "2026-05-22", desc: "Bitcoin Pizza Day 커뮤니티 이벤트 @FYI Center — 153+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "Collectible Con (Bangkok)", host: "The Concept Labs + Foksi + BammBamm", date: "2026-05-23", desc: "컬렉터블·NFT 커뮤니티 컨벤션 @True Digital Park — 35+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "Agentiq.Finance: From Prompt to Production", host: "Marek Michalski", date: "2026-05-20", desc: "AI 에이전트 파이낸스 SEABW 에디션 @Arcadia Barcade — Free", url: "https://luma.com/SEABW_Official" },
        { name: "Prediction Markets Rooftop Meetup", host: "Shard Bet", date: "2026-05-21", desc: "예측 시장 루프탑 밋업 @TRIBE Sky Beach Club — 28+ RSVP", url: "https://luma.com/SEABW_Official" },
        { name: "AI Future Ready", host: "Airova", date: "2026-05-19", desc: "AI 퓨처 레디 @SCBX NEXT TECH", url: "https://luma.com/SEABW_Official" },
        { name: "Blockconnect, Bangkok 🇹🇭", host: "Buildify", date: "2026-05-20", desc: "블록커넥트 방콕 에디션", url: "https://luma.com/SEABW_Official" },
      ],
    },
  },
  {
    id: "webx-2026-tokyo",
    name: "WebX 2026 Tokyo",
    city: "Tokyo",
    country: "Japan",
    date: "2026-07-13",
    endDate: "2026-07-14",
    days: 2,
    venue: "The Prince Park Tower, Tokyo",
    tier: "A",
    autoTier: "A",
    tierScore: 83,
    tierReasons: ["일본 최대 Web3 컨퍼런스", "CoinPost 주최", "일본 총리·장관 참석 사례"],
    gradient: "from-slate-100 via-white to-red-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/webx.sideevents",
    website: "https://webx-crypto.com/",
    cost: { flight: 350, hotel: 700, transport: 80, meals: 200, ticket: 300, total: 1630, note: "일반 패스 기준" },
    summary: {
      features: ["일본 최대 규모 Web3 국제 컨퍼런스", "CoinPost 기획·운영", "정치·금융·Web3 교차"],
      difference: ["일본 정부 최고위급 참석 (전년 총리·장관)", "일본 규제·정책 직접 체감", "아시아 전통 금융×Web3 교차"],
      pros: ["일본 Web3 정책·시그널 최전선", "가까운 거리 (항공 2시간)", "Uniswap·Galaxy 등 글로벌 연사"],
      risks: ["2026 날짜 미확정 (전년 8월 추정)", "일본어 중심 세션 가능", "엔화 약세로 비용 변동"],
      expectations: ["일본 Web3 정책 업데이트", "아시아 파트너십 탐색", "ETF·스테이블코인 규제 동향"],
    },
    feed: [
      { label: "2026 날짜 발표 대기", time: "현재", type: "일정" },
      { label: "Hayden Adams (Uniswap) 연사 예상", time: "전년 확인", type: "연사" },
      { label: "CoinPost 주최 확정", time: "상시", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "20,000+",
      sideEvents: 80,
      sponsors: 120,
      media: 60,
      eventTitle: "WebX 2025 Tokyo",
      notes: ["일본 최대 Web3 컨퍼런스", "이시바 총리, CZ, Arthur Hayes 참석", "20,000+ 참석자"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "일본/정책" },
      { label: "아카이브 성장", value: "+25%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "30일", detail: "90일 이상" },
    ],
    budget: [
      { label: "항공권", value: 350 },
      { label: "숙박", value: 700 },
      { label: "티켓", value: 300 },
      { label: "현지비", value: 280 },
    ],
    sideEventTrend: [
      { label: "2024", value: 55 },
      { label: "2025", value: 80 },
      { label: "2026", value: 3 },
    ],
    actions: ["2026 날짜 발표 모니터링", "일본 파트너 사전 리스트", "항공권 조기 예약"],
    companies: [
      { name: "0G (Zero Gravity)", tags: ["L1", "AI", "DA"], people: ["Team"], role: "⭐ AI 네이티브 L1 — 밸리데이터 모집 중", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 모집" },
      { name: "GenLayer", tags: ["L1", "AI", "LLM Consensus"], people: ["Team"], role: "⭐ LLM 기반 컨센서스 L1 — 테스트넷", isNew: true, layer: "L1", tgeDone: false, tgeNote: "TGE 전, 밸리데이터 모집" },
      { name: "CoinPost", tags: ["Media", "Organizer"], people: ["CEO"], role: "주최사", layer: "Media", tgeDone: true, tgeNote: "일본 최대 크립토 미디어" },
      { name: "SBI Holdings", tags: ["Finance", "Japan"], people: ["Yoshitaka Kitao (CEO)"], role: "일본 금융", layer: "TradFi", tgeDone: true, tgeNote: "일본 대형 금융" },
      { name: "Uniswap Labs", tags: ["DeFi", "Global"], people: ["Hayden Adams (Founder)"], role: "DeFi 인프라", isNew: true, layer: "DeFi", tgeDone: true, tgeNote: "UNI 토큰" },
      { name: "Startale Group", tags: ["Infra", "Japan"], people: ["Sota (CEO)"], role: "Web3 인프라", isNew: true, layer: "Infra", tgeDone: false, tgeNote: "일본 Web3 인프라" },
    ],
    sideEvents: {
      count: 3,
      label: "사이드 이벤트",
      items: [
        { name: "WebX 2026 Official Afterparty", host: "CoinPost / WebX Committee", date: "2026-07-13", desc: "WebX 검색 결과와 Luma 캘린더에 확인되는 공식 애프터파티" },
        { name: "VIP-only Activities", host: "CoinPost / WebX Committee", date: "2026-07-14", desc: "VIP 패스 대상 비공개 네트워킹·전용 액티비티" },
        { name: "WebX 2026 @Tokyo Luma Calendar", host: "CoinPost", date: "2026-07-13", desc: "CoinPost 운영 공식 Luma 캘린더 기반 사이드 이벤트 허브" },
      ],
    },
  },
  {
    id: "bitcoin-seoul-2026",
    name: "Bitcoin Seoul 2026",
    city: "Seoul",
    country: "South Korea",
    date: "2026-06-04",
    endDate: "2026-06-05",
    days: 2,
    venue: "FKI Tower (여의도)",
    tier: "B",
    autoTier: "B",
    tierScore: 68,
    tierReasons: ["한국 비트코인 전문 컨퍼런스", "정책·금융·기술 교차", "비트코인 커뮤니티 집결"],
    gradient: "from-orange-100 via-white to-yellow-100",
    status: "upcoming",
    isDomestic: true,
    imageUrl: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&h=300&fit=crop",
    website: "https://bitcoinseoul.kr/",
    cost: { flight: 0, hotel: 0, transport: 50, meals: 80, ticket: 100, total: 230, note: "국내 행사. 항공/숙박 불필요" },
    summary: {
      features: ["한국 비트코인 전문 컨퍼런스", "정책·금융·인권·기술 교차 논의", "비트코인 커뮤니티 집결지"],
      difference: ["비트코인 단일 자산 심층 집중", "한국 규제·정책 직접 체감", "글로벌 비트코인 인플루언서 참석"],
      pros: ["국내 비트코인 행사 — 부담 없는 참가", "한국 비트코인 커뮤니티 네트워킹", "Preston Pysh 등 글로벌 연사 참석 사례"],
      risks: ["2026 날짜 미확정 (추정)", "규모가 S급 대비 작음", "비트코인 외 프로토콜 관련성 제한"],
      expectations: ["한국 비트코인 규제 동향", "커뮤니티 네트워킹", "채굴·에너지 인프라 논의"],
    },
    feed: [
      { label: "서포터즈 30명 모집 마감 (5/11)", time: "2026-05-11", type: "모집" },
      { label: "2026 연사 라인업 곧 발표 예정", time: "2026-05-10", type: "연사" },
      { label: "전년 Preston Pysh·Dennis Porter 참석", time: "2025 참조", type: "연사" },
    ],
    archive: {
      year: "2025",
      attendees: "2,000+",
      sideEvents: 10,
      sponsors: 25,
      media: 15,
      eventTitle: "Bitcoin Seoul 2025",
      notes: ["한국 비트코인 전문 행사", "정책, 금융, 기술 교차 논의", "Preston Pysh, Dennis Porter 등 연사"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "BTC/커뮤니티" },
      { label: "국내 행사", value: "✓", detail: "서울" },
      { label: "업데이트 주기", value: "30일", detail: "90일 이상" },
    ],
    budget: [
      { label: "항공권", value: 0 },
      { label: "숙박", value: 0 },
      { label: "티켓", value: 100 },
      { label: "현지비", value: 130 },
    ],
    sideEventTrend: [
      { label: "2024", value: 6 },
      { label: "2025", value: 8 },
      { label: "2026", value: 0 },
    ],
    actions: ["6/4-5 참석 등록", "10% 할인코드(OnlyBS) 확인", "비트코인 커뮤니티 네트워킹 준비"],
    companies: [
      { name: "Sora Ventures", tags: ["VC", "Bitcoin"], people: ["Jason Fang (Partner)"], role: "투자", layer: "VC", tgeDone: true, tgeNote: "아시아 비트코인 VC" },
      { name: "Satoshi Action Fund", tags: ["Policy", "US"], people: ["Dennis Porter (CEO)"], role: "정책", layer: "Policy", tgeDone: false, tgeNote: "비트코인 정책 단체" },
      { name: "Seoul Economic Daily", tags: ["Media", "Korea"], people: ["CEO"], role: "미디어 파트너", layer: "Media", tgeDone: true, tgeNote: "한국 경제 미디어" },
    ],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트",
      items: [
      ],
    },
  },
  {
    id: "ethmilan-2026",
    name: "ETHMilan 2026",
    city: "Milan",
    country: "Italy",
    date: "2026-05-21",
    endDate: "2026-05-22",
    days: 2,
    venue: "Museo Nazionale della Scienza e della Tecnologia Leonardo da Vinci",
    tier: "B",
    autoTier: "B",
    tierScore: 69,
    tierReasons: ["이탈리아 최대 Ethereum/Web3 컨퍼런스", "2,000+ 참석자 예상", "100+ 연사"],
    gradient: "from-green-100 via-white to-red-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1513581166391-887a96ddeafd?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/ethmilan2026?k=c",
    website: "https://ethmilan.xyz/",
    cost: { flight: 750, hotel: 780, transport: 120, meals: 300, ticket: 350, total: 2300 },
    summary: {
      features: ["이탈리아 최대 Ethereum·Web3 컨퍼런스", "Leonardo da Vinci 과학박물관 베뉴", "Luma Crypto 허브 등재 (165 구독자)"],
      difference: ["이탈리아 Web3 생태계 직접 접근", "유럽 남부 규제·채택 인사이트", "학술·기술 혼합 컨퍼런스"],
      pros: ["유럽 이더리움 커뮤니티 네트워킹", "밀라노 접근성 좋음", "100+ 연사 다양한 트랙"],
      risks: ["규모가 S급 대비 작음", "이탈리아어 세션 가능", "남유럽 크립토 시장 규모 제한"],
      expectations: ["이탈리아 Web3 규제 동향", "유럽 이더리움 빌더 네트워킹", "DeFi·인프라 프로젝트 발굴"],
    },
    feed: [
      { label: "Luma Crypto 허브 등재 확인", time: "2026-05-07", type: "정보" },
      { label: "티켓 판매 중", time: "현재", type: "비용" },
    ],
    archive: {
      year: "2025",
      eventTitle: "ETHMilan 2025",
      attendees: "1,500+",
      sideEvents: 10,
      sponsors: 25,
      media: 12,
      notes: ["이탈리아 이더리움 커뮤니티 핵심 행사"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "ETH/유럽" },
      { label: "Luma 구독자", value: "165", detail: "Luma crypto hub" },
      { label: "업데이트 주기", value: "14일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 750 },
      { label: "숙박", value: 780 },
      { label: "티켓", value: 350 },
      { label: "현지비", value: 420 },
    ],
    sideEventTrend: [
      { label: "2025", value: 10 },
      { label: "2026", value: 0 },
    ],
    actions: ["티켓 구매 검토", "유럽 이더리움 파트너 리스트 작성"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma 등재, 상세 미공개",
      items: [],
    },
  },
  {
    id: "btc-prague-2026",
    name: "BTC Prague 2026",
    city: "Prague",
    country: "Czech Republic",
    date: "2026-06-11",
    endDate: "2026-06-13",
    days: 3,
    venue: "PVA EXPO Praha, Letňany",
    tier: "A",
    autoTier: "A",
    tierScore: 82,
    tierReasons: ["유럽 최대 비트코인 이벤트", "250+ 연사", "100+ 기업 참여"],
    gradient: "from-orange-100 via-white to-red-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/btc-prague?k=c",
    website: "https://btcprague.com/",
    cost: { flight: 750, hotel: 680, transport: 130, meals: 280, ticket: 499, total: 2339 },
    summary: {
      features: ["유럽 최대 비트코인 전용 컨퍼런스", "250+ 연사, 3개 스테이지", "PVA EXPO Praha 3일 행사"],
      difference: ["유럽 비트코인 커뮤니티 집결지", "비트코인 전용 — 다른 프로토콜 없음", "프라하 저비용 유럽 허브"],
      pros: ["유럽 비트코인 커뮤니티 최고 네트워킹", "프라하 접근성 및 비용 효율", "기술·정책·채굴 트랙 다양"],
      risks: ["비트코인 외 프로토콜 관련성 없음", "동유럽 접근 제한", "여름 관광 시즌 혼잡"],
      expectations: ["유럽 비트코인 채택 동향", "채굴 인프라 파트너십", "동유럽 규제 인사이트"],
    },
    feed: [
      { label: "티켓 판매 중 — 가격 인상 예정", time: "현재", type: "비용" },
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
    ],
    archive: {
      year: "2025",
      eventTitle: "BTC Prague 2025",
      attendees: "10,000+",
      sideEvents: 50,
      sponsors: 80,
      media: 40,
      notes: ["유럽 최대 비트코인 행사", "250+ 연사, 비트코인 기술·정책·채굴 집중"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "BTC/유럽" },
      { label: "아카이브 성장", value: "+15%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "7일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 750 },
      { label: "숙박", value: 680 },
      { label: "티켓", value: 499 },
      { label: "현지비", value: 410 },
    ],
    sideEventTrend: [
      { label: "2024", value: 35 },
      { label: "2025", value: 50 },
      { label: "2026", value: 55 },
    ],
    actions: ["티켓 조기 구매", "유럽 비트코인 파트너 리스트 작성", "프라하 숙박 예약"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "web3-summit-2026",
    name: "Web3 Summit 2026",
    city: "Berlin",
    country: "Germany",
    date: "2026-06-18",
    endDate: "2026-06-19",
    days: 2,
    venue: "Funkhaus Berlin",
    tier: "B",
    autoTier: "B",
    tierScore: 70,
    tierReasons: ["베를린 Web3 커뮤니티 집결", "Funkhaus Berlin 베뉴", "Luma Crypto 허브 등재"],
    gradient: "from-gray-100 via-white to-yellow-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/web3-summit?k=c",
    website: "https://web3summit.com/",
    cost: { flight: 700, hotel: 650, transport: 120, meals: 280, ticket: 399, total: 2149 },
    summary: {
      features: ["베를린 Web3 서밋", "Funkhaus Berlin 아이코닉 베뉴", "Luma Crypto 허브 Launching Soon 등재"],
      difference: ["베를린 Web3 생태계 직접 접근", "프로토콜 빌더·연구자 중심", "독일 규제 인사이트"],
      pros: ["베를린 크립토 허브 네트워킹", "유럽 빌더 커뮤니티 접근", "비교적 합리적 비용"],
      risks: ["규모 정보 제한적", "독일어 세션 가능", "Launching Soon 상태"],
      expectations: ["유럽 Web3 생태계 파악", "프로토콜 기술 논의", "독일 규제 동향"],
    },
    feed: [
      { label: "티켓 판매 중 (crypto/fiat)", time: "현재", type: "비용" },
      { label: "Luma Crypto Launching Soon 등재", time: "2026-05-07", type: "정보" },
    ],
    archive: {
      year: "2025",
      eventTitle: "Web3 Summit 2025",
      attendees: "2,000+",
      sideEvents: 15,
      sponsors: 30,
      media: 15,
      notes: ["베를린 Web3 커뮤니티 행사"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "Web3/유럽" },
      { label: "업데이트 주기", value: "14일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 700 },
      { label: "숙박", value: 650 },
      { label: "티켓", value: 399 },
      { label: "현지비", value: 400 },
    ],
    sideEventTrend: [
      { label: "2025", value: 15 },
      { label: "2026", value: 17 },
    ],
    actions: ["티켓 구매 검토", "베를린 파트너 리스트 작성"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "dutch-blockchain-week-2026",
    name: "Dutch Blockchain Week 2026",
    city: "Amsterdam",
    country: "Netherlands",
    date: "2026-06-22",
    endDate: "2026-06-28",
    days: 7,
    venue: "Johan Cruijff ArenA (Summit Jun 24-25)",
    tier: "A",
    autoTier: "A",
    tierScore: 78,
    tierReasons: ["유럽 선도 B2B 블록체인 위크", "Johan Cruijff ArenA 베뉴", "거래소·은행·규제기관 집결"],
    gradient: "from-orange-100 via-white to-blue-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/dutchblockchainweek?k=c",
    website: "https://dutchblockchainweek.com/",
    cost: { flight: 700, hotel: 850, transport: 120, meals: 320, ticket: 599, total: 2589 },
    summary: {
      features: ["유럽 선도 B2B 블록체인 위크", "Johan Cruijff ArenA 서밋 (6/24-25)", "거래소, 은행, 규제기관, 마켓메이커 집결"],
      difference: ["B2B 집중 — 기관·규제 중심", "네덜란드 금융 허브 직접 접근", "7일 위크 + 2일 서밋 구조"],
      pros: ["유럽 기관 네트워킹 최적", "암스테르담 접근성 우수", "거래소·펀드 밀도 높음"],
      risks: ["B2B 포커스라 소규모 프로젝트 접근 어려움", "암스테르담 호텔 비쌈", "Launching Soon 상태"],
      expectations: ["유럽 규제 프레임워크 파악", "기관 파트너십 탐색", "마켓메이커·OTC 네트워킹"],
    },
    feed: [
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
      { label: "서밋 6/24-25 확정", time: "현재", type: "일정" },
    ],
    archive: {
      year: "2025",
      eventTitle: "Dutch Blockchain Week 2025",
      attendees: "5,000+",
      sideEvents: 30,
      sponsors: 60,
      media: 25,
      notes: ["유럽 B2B 블록체인 행사", "기관 중심"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "기관/유럽" },
      { label: "업데이트 주기", value: "14일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 700 },
      { label: "숙박", value: 850 },
      { label: "티켓", value: 599 },
      { label: "현지비", value: 440 },
    ],
    sideEventTrend: [
      { label: "2025", value: 30 },
      { label: "2026", value: 34 },
    ],
    actions: ["서밋 티켓 구매 검토", "네덜란드 기관 파트너 리스트 작성"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "ivs-2026",
    name: "IVS 2026",
    city: "Kyoto",
    country: "Japan",
    date: "2026-07-01",
    endDate: "2026-07-03",
    days: 3,
    venue: "Kyoto Convention Center + Hotel Okura Kyoto",
    tier: "A",
    autoTier: "A",
    tierScore: 80,
    tierReasons: ["일본 최대 스타트업 컨퍼런스", "13,000+ 참석자 / 70+ 국가", "교토 컨벤션 센터"],
    gradient: "from-red-100 via-white to-pink-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/ivs?k=c",
    website: "https://ivs.events/",
    cost: { flight: 350, hotel: 650, transport: 100, meals: 250, ticket: 400, total: 1750 },
    summary: {
      features: ["일본 최대 스타트업 컨퍼런스 (크립토 트랙 포함)", "13,000+ 참석자, 70+ 국가", "교토 컨벤션 센터 + 호텔 오쿠라"],
      difference: ["스타트업 전반 + 크립토/Web3 트랙", "일본 VC·기업 접근 최적", "교토 문화 체험 병행"],
      pros: ["일본 스타트업 생태계 원스톱", "크립토 트랙에서 일본 규제 논의", "가까운 거리 (항공 2시간)"],
      risks: ["크립토 전용 행사 아님", "일본어 세션 다수", "교토 여름 더위"],
      expectations: ["일본 Web3 규제·정책 파악", "일본 VC·기업 네트워킹", "아시아 스타트업 트렌드"],
    },
    feed: [
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
      { label: "13,000+ 참석자 예상", time: "현재", type: "참석자" },
    ],
    archive: {
      year: "2025",
      eventTitle: "IVS 2025",
      attendees: "13,000+",
      sideEvents: 40,
      sponsors: 80,
      media: 50,
      notes: ["일본 최대 스타트업 컨퍼런스", "크립토 트랙 포함"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "일본/스타트업" },
      { label: "업데이트 주기", value: "14일", detail: "60일 이내" },
    ],
    budget: [
      { label: "항공권", value: 350 },
      { label: "숙박", value: 650 },
      { label: "티켓", value: 400 },
      { label: "현지비", value: 350 },
    ],
    sideEventTrend: [
      { label: "2025", value: 40 },
      { label: "2026", value: 45 },
    ],
    actions: ["티켓 구매 검토", "일본 파트너 리스트 작성", "교토 숙박 예약"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "blockchain-rio-2026",
    name: "Blockchain Rio 2026",
    city: "Rio de Janeiro",
    country: "Brazil",
    date: "2026-08-11",
    endDate: "2026-08-13",
    days: 3,
    venue: "ExpoRio + Leaders Casa Camolese",
    tier: "B",
    autoTier: "B",
    tierScore: 68,
    tierReasons: ["남미 대표 블록체인 행사", "Luma Crypto 허브 등재", "리우 3일 행사"],
    gradient: "from-green-100 via-white to-yellow-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/blockchain-rio?k=c",
    website: "https://blockchainrio.com.br/",
    cost: { flight: 1200, hotel: 600, transport: 100, meals: 200, ticket: 350, total: 2450 },
    summary: {
      features: ["남미 대표 블록체인 컨퍼런스", "ExpoRio + Leaders Casa Camolese 베뉴", "8/11 리더스 서밋 + 8/12-13 메인 엑스포"],
      difference: ["남미 시장 직접 접근", "브라질 크립토 채택 최전선", "리우 접근성"],
      pros: ["남미 크립토 생태계 파악", "브라질 규제 인사이트", "저비용 현지 체류"],
      risks: ["장거리 항공 (ICN→GIG)", "포르투갈어 세션 가능", "남미 규제 불확실성"],
      expectations: ["남미 크립토 채택 동향", "브라질 파트너십 탐색", "LatAm 규제 프레임워크"],
    },
    feed: [
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
    ],
    archive: {
      year: "2025",
      eventTitle: "Blockchain Rio 2025",
      attendees: "5,000+",
      sideEvents: 20,
      sponsors: 40,
      media: 20,
      notes: ["남미 최대 블록체인 행사"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "남미/신흥" },
      { label: "업데이트 주기", value: "30일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 1200 },
      { label: "숙박", value: 600 },
      { label: "티켓", value: 350 },
      { label: "현지비", value: 300 },
    ],
    sideEventTrend: [
      { label: "2025", value: 20 },
      { label: "2026", value: 23 },
    ],
    actions: ["항공편 비용 모니터링", "남미 파트너 리스트 작성"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "coinfest-asia-2026",
    name: "Coinfest Asia 2026",
    city: "Bali",
    country: "Indonesia",
    date: "2026-08-20",
    endDate: "2026-08-21",
    days: 2,
    venue: "Melasti Beach, Bali",
    tier: "B",
    autoTier: "B",
    tierScore: 67,
    tierReasons: ["세계 최대 크립토 페스티벌", "Luma Crypto 허브 등재", "발리 비치 베뉴"],
    gradient: "from-cyan-100 via-white to-green-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/coinfest-asia?k=c",
    website: "https://coinfest.asia/",
    cost: { flight: 550, hotel: 400, transport: 80, meals: 150, ticket: 299, total: 1479 },
    summary: {
      features: ["세계 최대 크립토 페스티벌 표방", "발리 Melasti Beach 야외 베뉴", "동남아 크립토 커뮤니티 집결"],
      difference: ["페스티벌 형식 — 컨퍼런스보다 캐주얼", "발리 비치 베뉴 독특한 경험", "동남아 시장 접근"],
      pros: ["저비용 동남아 참여", "캐주얼 네트워킹 기회", "인도네시아 크립토 시장 접근"],
      risks: ["페스티벌 형식으로 BD 효율 제한", "발리 접근성 (환승 필요)", "Launching Soon 상태"],
      expectations: ["동남아 크립토 트렌드 파악", "인도네시아 시장 인사이트", "캐주얼 네트워킹"],
    },
    feed: [
      { label: "얼리버드 티켓 판매 중", time: "현재", type: "비용" },
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
    ],
    archive: {
      year: "2025",
      eventTitle: "Coinfest Asia 2025",
      attendees: "5,000+",
      sideEvents: 15,
      sponsors: 30,
      media: 15,
      notes: ["발리 크립토 페스티벌"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "동남아/커뮤니티" },
      { label: "업데이트 주기", value: "30일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 550 },
      { label: "숙박", value: 400 },
      { label: "티켓", value: 299 },
      { label: "현지비", value: 230 },
    ],
    sideEventTrend: [
      { label: "2025", value: 15 },
      { label: "2026", value: 17 },
    ],
    actions: ["얼리버드 티켓 검토", "발리 항공편 모니터링"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "ethrome-2026",
    name: "ETHRome 2026",
    city: "Rome",
    country: "Italy",
    date: "2026-09-11",
    endDate: "2026-09-13",
    days: 3,
    venue: "Talent Garden Roma, Via Ostiense 92",
    tier: "B",
    autoTier: "B",
    tierScore: 66,
    tierReasons: ["이탈리아 이더리움 해커톤", "빌더 중심 행사", "Luma Crypto 허브 등재"],
    gradient: "from-amber-100 via-white to-green-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1529260830199-42c24126f198?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/ethrome?k=c",
    website: "https://ethrome.org/",
    cost: { flight: 750, hotel: 680, transport: 120, meals: 280, ticket: 0, total: 1830, note: "해커톤 참가비 무료 예상" },
    summary: {
      features: ["이탈리아 대표 이더리움 해커톤", "AI, DeFi & Privacy 트랙", "Talent Garden Roma 베뉴"],
      difference: ["해커톤 중심 — 컨퍼런스 아닌 빌더 행사", "로마 소규모 고밀도", "이탈리아 빌더 커뮤니티"],
      pros: ["빌더 네트워킹 최적", "해커톤 참가비 무료 예상", "로마 문화 체험"],
      risks: ["해커톤이라 BD 기회 제한", "규모 작음", "개발자 중심이라 투자 논의 제한"],
      expectations: ["이더리움 빌더 네트워킹", "AI·DeFi·Privacy 기술 동향", "해커톤 프로젝트 발굴"],
    },
    feed: [
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
    ],
    archive: {
      year: "2025",
      eventTitle: "ETHRome 2025",
      attendees: "500+",
      sideEvents: 5,
      sponsors: 15,
      media: 8,
      notes: ["이더리움 빌더 해커톤"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "빌더/해커톤" },
      { label: "업데이트 주기", value: "30일", detail: "90일 이상" },
    ],
    budget: [
      { label: "항공권", value: 750 },
      { label: "숙박", value: 680 },
      { label: "티켓", value: 0 },
      { label: "현지비", value: 400 },
    ],
    sideEventTrend: [
      { label: "2025", value: 5 },
      { label: "2026", value: 6 },
    ],
    actions: ["해커톤 참가 신청 모니터링"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "token2049-singapore-2026",
    name: "TOKEN2049 Singapore 2026",
    city: "Singapore",
    country: "Singapore",
    date: "2026-10-07",
    endDate: "2026-10-08",
    days: 2,
    venue: "Singapore (상세 TBA)",
    tier: "S",
    autoTier: "S",
    tierScore: 92,
    tierReasons: ["세계 최대 크립토 이벤트 시리즈", "15,000+ 참석자 예상", "아시아 금융 허브"],
    gradient: "from-purple-100 via-white to-cyan-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/token2049?k=c",
    website: "https://www.token2049.com/",
    cost: { flight: 550, hotel: 1100, transport: 120, meals: 300, ticket: 799, total: 2869 },
    summary: {
      features: ["세계 최대 크립토 이벤트 시리즈 싱가포르 에디션", "15,000+ 참석자 예상", "아시아 금융 허브 싱가포르"],
      difference: ["글로벌 최대 규모 — 기관+빌더 통합", "아시아 자본 집결지", "두바이 에디션 취소로 유일한 TOKEN2049"],
      pros: ["아시아 최대 크립토 네트워킹", "기관·거래소·펀드 밀도 최고", "싱가포르 접근성 우수"],
      risks: ["프리미엄 패스 가격 높음", "싱가포르 호텔 비쌈", "행사 규모가 커 타겟팅 필요"],
      expectations: ["글로벌 크립토 트렌드 파악", "아시아 기관 파트너십", "거래소·마켓메이커 네트워킹"],
    },
    feed: [
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
      { label: "2026년 10/7-8 확정", time: "현재", type: "일정" },
    ],
    archive: {
      year: "2025",
      eventTitle: "TOKEN2049 Singapore 2025",
      attendees: "25,000+",
      sideEvents: 1000,
      sponsors: 500,
      media: 100,
      notes: ["세계 최대 크립토 이벤트", "25,000+ 참석자, 1,000+ 사이드 이벤트, 500+ 스폰서"],
    },
    kpis: [
      { label: "미팅 적합도", value: "매우 높음", detail: "전 분야" },
      { label: "아카이브 성장", value: "+20%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "60일 이내" },
    ],
    budget: [
      { label: "항공권", value: 550 },
      { label: "숙박", value: 1100 },
      { label: "티켓", value: 799 },
      { label: "현지비", value: 420 },
    ],
    sideEventTrend: [
      { label: "2023", value: 120 },
      { label: "2024", value: 170 },
      { label: "2025", value: 1000 },
      { label: "2026", value: 1150 },
    ],
    actions: ["티켓 사전 구매 검토", "싱가포르 숙박 조기 예약", "기관/VC 타겟 리스트 작성"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "devcon-8-mumbai",
    name: "Devcon 8 (Mumbai)",
    city: "Mumbai",
    country: "India",
    date: "2026-11-03",
    endDate: "2026-11-06",
    days: 4,
    venue: "Jio World Centre, Bandra Kurla Complex",
    tier: "S",
    autoTier: "S",
    tierScore: 91,
    tierReasons: ["이더리움 재단 공식 컨퍼런스", "10,000+ 개발자·연구자", "4일간 개최"],
    gradient: "from-indigo-100 via-white to-violet-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/devcon?k=c",
    website: "https://devcon.org/",
    cost: { flight: 650, hotel: 600, transport: 100, meals: 180, ticket: 200, total: 1730, note: "일반 티켓 기준 추정" },
    summary: {
      features: ["이더리움 재단 공식 개발자 컨퍼런스", "Jio World Centre 4일 행사", "전 세계 이더리움 빌더·연구자 집결"],
      difference: ["이더리움 전용 — 다른 L1 없음", "개발자·연구자 중심 최고 밀도", "인도 신흥 시장 직접 접근"],
      pros: ["이더리움 생태계 최고 행사", "인도 Web3 시장 접근", "기술 심도 최고"],
      risks: ["이더리움 외 관련성 제한", "인도 비자 필요", "뭄바이 11월 고온다습"],
      expectations: ["이더리움 로드맵 업데이트", "빌더 네트워킹", "인도 Web3 시장 인사이트"],
    },
    feed: [
      { label: "Jio World Centre 베뉴 확정", time: "현재", type: "운영" },
      { label: "Luma Crypto 허브 Launching Soon 등재", time: "2026-05-07", type: "정보" },
    ],
    archive: {
      year: "2024",
      eventTitle: "Devcon 7 (Bangkok)",
      attendees: "12,000+",
      sideEvents: 150,
      sponsors: 100,
      media: 80,
      notes: ["방콕 QSNCC 개최", "이더리움 개발자 최대 집결"],
    },
    kpis: [
      { label: "미팅 적합도", value: "매우 높음", detail: "ETH/개발자" },
      { label: "아카이브 성장", value: "+15%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 650 },
      { label: "숙박", value: 600 },
      { label: "티켓", value: 200 },
      { label: "현지비", value: 280 },
    ],
    sideEventTrend: [
      { label: "2022", value: 80 },
      { label: "2023", value: 100 },
      { label: "2024", value: 150 },
      { label: "2026", value: 170 },
    ],
    actions: ["티켓 사전 구매 검토", "인도 비자 확인", "뭄바이 숙박 조기 예약"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 — Luma Launching Soon, 상세 미공개",
      items: [],
    },
  },
  {
    id: "conviction-2026",
    name: "Conviction 2026",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    date: "2026-05-08",
    endDate: "2026-05-09",
    days: 2,
    venue: "Thiskyhall Sala Convention Center",
    tier: "B",
    autoTier: "B",
    tierScore: 68,
    tierReasons: ["베트남 최대 블록체인 서밋", "Resolution 05/2025 및 디지털 자산법 포커스", "1,500명 참석 예상"],
    gradient: "from-red-100 via-white to-yellow-100",
    status: "completed",
    imageUrl: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/conviction2026",
    website: "https://www.conviction.vn/",
    cost: { flight: 450, hotel: 400, transport: 80, meals: 200, ticket: 399, total: 1529 },
    summary: {
      features: ["베트남 프리미어 블록체인·디지털 자산 서밋", "Resolution 05/2025 및 베트남 디지털 자산법 2026 집중", "기관 대상 규제 프레임워크 논의", "베트남 공식 인정 디지털 자산 경제 포럼"],
      difference: ["베트남 규제·정책 특화", "동남아 시장 진출 교두보", "기관 배포 중심", "정책-정렬 채택(policy-aligned adoption) 포커스"],
      pros: ["동남아 시장 직접 탐색", "비교적 저렴한 참가비", "베트남 디지털 자산 정책 최신 동향"],
      risks: ["글로벌 영향력 제한", "첫 대규모 에디션 불확실성", "영어 세션 비율 확인 필요"],
      expectations: ["베트남 디지털 자산 규제 파악", "동남아 파트너십 탐색", "기관 채택 현황"],
    },
    feed: [
      { label: "행사 종료 (Day 2)", time: "2026-05-09", type: "완료" },
      { label: "디지털 자산 경제 포럼 진행", time: "2026-05-08", type: "메인" },
      { label: "베트남 정책입안자 세션", time: "2026-05-08", type: "규제" },
    ],
    archive: {
      year: "2026",
      attendees: "1,500+",
      sideEvents: 5,
      sponsors: 30,
      media: 15,
      eventTitle: "Conviction 2026",
      notes: ["베트남 공식 인정 포럼 — 디지털 자산 경제 정책 논의", "Resolution 05/2025 기반 규제 프레임워크 논의", "동남아 시장 진출 교두보"],
    },
    kpis: [
      { label: "미팅 적합도", value: "중간", detail: "동남아/규제" },
      { label: "아카이브 성장", value: "N/A", detail: "첫 대규모 에디션" },
      { label: "업데이트 주기", value: "14일", detail: "60일 이내" },
    ],
    budget: [
      { label: "항공권", value: 450 },
      { label: "숙박", value: 400 },
      { label: "티켓", value: 399 },
      { label: "현지비", value: 280 },
    ],
    sideEventTrend: [],
    actions: ["행사 종료 — 주요 미팅 결과 정리", "베트남 파트너십 후속 진행", "SEABW 방콕 (5/18) 연계 탐색"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 미공개",
      items: [{ name: "Side events not yet announced", host: "TBA", date: "2026-05-08", desc: "사이드 이벤트 미공개" }],
    },
  },
  {
    id: "proof-of-talk-2026",
    name: "Proof of Talk 2026",
    city: "Paris",
    country: "France",
    date: "2026-06-02",
    endDate: "2026-06-03",
    days: 2,
    venue: "Louvre Palace (Palais du Louvre)",
    tier: "A",
    autoTier: "A",
    tierScore: 82,
    tierReasons: ["Web3의 다보스", "90% C-suite 참석", "루브르 궁전 프리미엄 베뉴"],
    gradient: "from-blue-100 via-white to-indigo-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/proofoftalk",
    website: "https://proofoftalk.io/",
    cost: { flight: 850, hotel: 1200, transport: 150, meals: 400, ticket: 1499, total: 4099 },
    summary: {
      features: ["Web3의 다보스 — 프리미어 경영진 컨퍼런스", "2,500명 의사결정권자, 120명 연사, 90% C-suite", "루브르 궁전에서 개최"],
      difference: ["No pay-to-speak 정책", "StableDay — 스테이블코인 전용 서밋 포함", "Securitize, Swift, Franklin Templeton, Aave, Mastercard 등 리더 참여"],
      pros: ["최상위 경영진 네트워킹", "프리미엄 베뉴 — 루브르 궁전", "스테이블코인 밸류체인 전문 세션"],
      risks: ["높은 티켓 가격", "파리 숙박비 비쌈", "초대 전용 세션 접근 제한 가능"],
      expectations: ["기관 채택 전략 파악", "스테이블코인 밸류체인 인사이트", "C-suite 네트워킹"],
    },
    feed: [
      { label: "StableDay 프로그램 발표", time: "2주 전", type: "아젠다" },
      { label: "연사 라인업 완성", time: "1개월 전", type: "연사" },
      { label: "루브르 궁전 베뉴 확정", time: "3개월 전", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "2,000+",
      sideEvents: 8,
      sponsors: 40,
      media: 25,
      eventTitle: "Proof of Talk 2025",
      notes: ["Web3 경영진 최고 밀도 행사", "C-suite 참여율 90%"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "C-suite/기관" },
      { label: "아카이브 성장", value: "+25%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "7일", detail: "30일 이내" },
    ],
    budget: [
      { label: "항공권", value: 850 },
      { label: "숙박", value: 1200 },
      { label: "티켓", value: 1499 },
      { label: "현지비", value: 550 },
    ],
    sideEventTrend: [
      { label: "2024", value: 5 },
      { label: "2025", value: 8 },
      { label: "2026", value: 3 },
    ],
    actions: ["티켓 사전 구매 — 프리미엄 가격", "파리 호텔 조기 예약", "StableDay 세션 참석 계획"],
    companies: [
      { name: "Securitize", tags: ["RWA", "Tokenization"], people: ["CEO"], role: "토큰화", layer: "Infra", tgeDone: true, tgeNote: "DS Protocol" },
      { name: "Aave", tags: ["DeFi", "Lending"], people: ["Founder"], role: "DeFi 인프라", layer: "DeFi", tgeDone: true, tgeNote: "AAVE 토큰" },
      { name: "Mastercard", tags: ["TradFi", "Payments"], people: ["Crypto Lead"], role: "결제 인프라", layer: "TradFi", tgeDone: false, tgeNote: "전통 금융" },
      { name: "Dragonfly", tags: ["VC"], people: ["Partner"], role: "투자", layer: "VC", tgeDone: true, tgeNote: "펀드 자본" },
    ],
    sideEvents: {
      count: 3,
      label: "사이드 이벤트",
      items: [
        { name: "StableDay — Stablecoin Summit", host: "Proof of Talk", date: "2026-06-03", desc: "스테이블코인 밸류체인 전용 서밋" },
        { name: "VIP Networking Dinner", host: "Proof of Talk", date: "2026-06-02", desc: "VIP 네트워킹 디너" },
        { name: "Executive Roundtables", host: "Proof of Talk", date: "2026-06-02", desc: "경영진 라운드테이블 워크숍" },
      ],
    },
  },
  {
    id: "ebc-barcelona-2026",
    name: "European Blockchain Convention 2026",
    city: "Barcelona",
    country: "Spain",
    date: "2026-09-16",
    endDate: "2026-09-17",
    days: 2,
    venue: "Fira Barcelona Montjuïc",
    tier: "A",
    autoTier: "A",
    tierScore: 80,
    tierReasons: ["유럽 최대 블록체인 페스티벌", "12회차", "70개국 6,000+ 참석자"],
    gradient: "from-yellow-100 via-white to-red-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/european-blockchain-convention",
    website: "https://eblockchainconvention.com/",
    cost: { flight: 800, hotel: 900, transport: 120, meals: 350, ticket: 699, total: 2869 },
    summary: {
      features: ["유럽 최대 블록체인·크립토·Web3 페스티벌", "12회차 — 70개국 6,000+ 참석자", "주요 투자펀드, 은행, 인프라 기업, 규제 기관 참여"],
      difference: ["유럽 규제 프레임워크(MiCA) 포커스", "전통 금융 기관 참여 비율 높음", "빌더, 투자자, TradFi 리더 혼합"],
      pros: ["유럽 시장 네트워킹 최적", "바르셀로나 접근성 좋음", "규제·기관 인사이트 풍부"],
      risks: ["S급 대비 글로벌 영향력 제한", "바르셀로나 여름 호텔 경쟁", "유럽 외 참석자 비율 낮을 수 있음"],
      expectations: ["유럽 규제 동향 파악", "기관 파트너십 탐색", "TradFi-크립토 교차점 인사이트"],
    },
    feed: [
      { label: "얼리버드 티켓 오픈", time: "2개월 전", type: "비용" },
      { label: "스피커 라인업 1차 발표", time: "1개월 전", type: "연사" },
      { label: "Fira Barcelona 베뉴 확정", time: "4개월 전", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "5,000+",
      sideEvents: 20,
      sponsors: 80,
      media: 40,
      eventTitle: "European Blockchain Convention 2025",
      notes: ["유럽 블록체인 커뮤니티 핵심 행사", "MiCA 규제 논의 활발"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "유럽/기관" },
      { label: "아카이브 성장", value: "+20%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 800 },
      { label: "숙박", value: 900 },
      { label: "티켓", value: 699 },
      { label: "현지비", value: 470 },
    ],
    sideEventTrend: [
      { label: "2024", value: 15 },
      { label: "2025", value: 20 },
      { label: "2026", value: 23 },
    ],
    actions: ["얼리버드 티켓 등록", "유럽 파트너 리스트 준비", "MiCA 규제 브리핑"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 미공개",
      items: [{ name: "Side events not yet announced", host: "TBA", date: "2026-09-16", desc: "사이드 이벤트 미공개" }],
    },
  },
  {
    id: "bitcoin-amsterdam-2026",
    name: "Bitcoin Amsterdam 2026",
    city: "Amsterdam",
    country: "Netherlands",
    date: "2026-11-05",
    endDate: "2026-11-06",
    days: 2,
    venue: "Amsterdam (venue TBA)",
    tier: "A",
    autoTier: "A",
    tierScore: 78,
    tierReasons: ["유럽 플래그십 비트코인 컨퍼런스", "빌더·투자자·개발자·옹호자 집결", "3,000명 참석 예상"],
    gradient: "from-orange-100 via-white to-blue-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/bitcoin-amsterdam",
    website: "https://www.bitcoin.amsterdam/2026",
    cost: { flight: 820, hotel: 1000, transport: 130, meals: 380, ticket: 599, total: 2929 },
    summary: {
      features: ["유럽 플래그십 비트코인 컨퍼런스", "빌더, 투자자, 개발자, 옹호자 집결", "비트코인 생태계 현황 및 미래 탐구"],
      difference: ["비트코인 단일 자산 집중", "유럽 비트코인 커뮤니티 핵심", "사상 리더, 기업가, 채굴자 참여"],
      pros: ["유럽 비트코인 네트워킹 최적", "암스테르담 접근성 우수", "비트코인 전문가 밀도 높음"],
      risks: ["베뉴 미확정", "비트코인 외 프로토콜 관련성 낮음", "11월 암스테르담 날씨"],
      expectations: ["유럽 비트코인 채택 동향", "채굴 및 인프라 파트너십", "커뮤니티 네트워킹"],
    },
    feed: [
      { label: "2026 에디션 공식 발표", time: "2개월 전", type: "공지" },
      { label: "얼리버드 티켓 오픈", time: "1개월 전", type: "비용" },
    ],
    archive: {
      year: "2025",
      attendees: "2,500+",
      sideEvents: 15,
      sponsors: 50,
      media: 25,
      eventTitle: "Bitcoin Amsterdam 2025",
      notes: ["유럽 비트코인 핵심 행사", "채굴·인프라·커뮤니티 집중"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "비트코인/유럽" },
      { label: "아카이브 성장", value: "+20%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 820 },
      { label: "숙박", value: 1000 },
      { label: "티켓", value: 599 },
      { label: "현지비", value: 510 },
    ],
    sideEventTrend: [
      { label: "2024", value: 10 },
      { label: "2025", value: 15 },
      { label: "2026", value: 17 },
    ],
    actions: ["베뉴 확정 모니터링", "얼리버드 티켓 등록", "유럽 비트코인 파트너 리스트"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 미공개",
      items: [{ name: "Side events not yet announced", host: "TBA", date: "2026-11-05", desc: "사이드 이벤트 미공개" }],
    },
  },
  {
    id: "aus-crypto-con-2026",
    name: "Australian Crypto Convention 2026",
    city: "Sydney",
    country: "Australia",
    date: "2026-11-28",
    endDate: "2026-11-29",
    days: 2,
    venue: "International Convention Centre (ICC) Sydney",
    tier: "A",
    autoTier: "A",
    tierScore: 81,
    tierReasons: ["남반구 최대 크립토 이벤트", "5회차 — 10,000+ 참석자", "15+ 사이드 이벤트"],
    gradient: "from-green-100 via-white to-yellow-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/australian-crypto-convention",
    website: "https://auscryptocon.com/",
    cost: { flight: 950, hotel: 1100, transport: 150, meals: 400, ticket: 599, total: 3199 },
    summary: {
      features: ["남반구 최대 크립토·블록체인 이벤트", "5회차 — 10,000+ 참석자, 120+ 스폰서", "150+ 연사, 5+ 스테이지, 15+ 사이드 이벤트"],
      difference: ["크립토 드론쇼 by Swyftx", "시드니 하버 슈퍼요트 애프터파티", "오세아니아 시장 직접 접근"],
      pros: ["남반구 최대 규모 크립토 행사", "호주 규제 인사이트", "독특한 네트워킹 경험 (드론쇼, 요트)"],
      risks: ["인천에서 장거리 비행", "호주 비자 필요 확인", "시드니 숙박비 높음"],
      expectations: ["호주 크립토 생태계 파악", "오세아니아 파트너십 탐색", "규제 동향 확인"],
    },
    feed: [
      { label: "얼리버드 티켓 오픈", time: "3개월 전", type: "비용" },
      { label: "드론쇼 파트너 발표", time: "2개월 전", type: "아젠다" },
      { label: "ICC Sydney 베뉴 확정", time: "4개월 전", type: "운영" },
    ],
    archive: {
      year: "2025",
      attendees: "8,000+",
      sideEvents: 12,
      sponsors: 100,
      media: 40,
      eventTitle: "Australian Crypto Convention 2025",
      notes: ["남반구 최대 크립토 행사", "호주 규제 환경 개선으로 성장세"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "오세아니아/크립토" },
      { label: "아카이브 성장", value: "+25%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "14일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 950 },
      { label: "숙박", value: 1100 },
      { label: "티켓", value: 599 },
      { label: "현지비", value: 550 },
    ],
    sideEventTrend: [
      { label: "2024", value: 8 },
      { label: "2025", value: 12 },
      { label: "2026", value: 15 },
    ],
    actions: ["호주 비자 확인", "얼리버드 티켓 등록", "시드니 호텔 조기 예약"],
    companies: [],
    sideEvents: {
      count: 15,
      label: "사이드 이벤트",
      items: [
        { name: "Official After Party — Super Yacht Sydney Harbour", host: "Australian Crypto Convention", date: "2026-11-29", desc: "오픈 바, 큐레이션 음식, VIP 라운지, 엔터테인먼트" },
        { name: "Crypto Drone Show by Swyftx", host: "Swyftx", date: "2026-11-28", desc: "크립토 드론쇼 엔터테인먼트" },
        { name: "Workshops & Bootcamps", host: "Australian Crypto Convention", date: "2026-11-28", desc: "워크숍 및 부트캠프" },
      ],
    },
  },
  {
    id: "blockchain-life-2026",
    name: "Blockchain Life 2026",
    city: "Dubai",
    country: "United Arab Emirates",
    date: "2026-12-01",
    endDate: "2026-12-02",
    days: 2,
    venue: "Dubai (venue TBA)",
    tier: "S",
    autoTier: "S",
    tierScore: 88,
    tierReasons: ["세계 Top 2 크립토 이벤트", "17회차 — 130개국 15,000+ 참석자", "200+ 연사"],
    gradient: "from-purple-100 via-white to-amber-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/blockchain-life",
    website: "https://blockchain-life.com/autumn2026/",
    cost: { flight: 760, hotel: 1400, transport: 180, meals: 400, ticket: 999, total: 3739 },
    summary: {
      features: ["17회차 국제 Web3·크립토·채굴 포럼", "세계 Top 2 크립토 이벤트", "130개국 15,000+ 참석자, 200+ 연사"],
      difference: ["전시, 네트워킹, 스타트업 경쟁 포함", "크립토 고래, 창업자 밀도 높음", "Web3 전 분야 포괄"],
      pros: ["글로벌 최상위 규모", "두바이 생태계 접근", "투자자·창업자 밀도 높음"],
      risks: ["베뉴 미확정", "두바이 호텔 가격 변동", "대규모 행사 타겟팅 어려움"],
      expectations: ["글로벌 크립토 트렌드 파악", "투자자 네트워킹", "스타트업 파이프라인 발굴"],
    },
    feed: [
      { label: "2026 가을 에디션 발표", time: "2개월 전", type: "공지" },
      { label: "슈퍼 얼리버드 오픈", time: "1개월 전", type: "비용" },
    ],
    archive: {
      year: "2025",
      attendees: "12,000+",
      sideEvents: 30,
      sponsors: 150,
      media: 60,
      eventTitle: "Blockchain Life 2025",
      notes: ["글로벌 Top 2 크립토 포럼", "130개국 참석자, 200+ 연사"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "글로벌/투자자" },
      { label: "아카이브 성장", value: "+25%", detail: "참석자 YoY" },
      { label: "업데이트 주기", value: "7일", detail: "60일 이내" },
    ],
    budget: [
      { label: "항공권", value: 760 },
      { label: "숙박", value: 1400 },
      { label: "티켓", value: 999 },
      { label: "현지비", value: 580 },
    ],
    sideEventTrend: [
      { label: "2024", value: 20 },
      { label: "2025", value: 30 },
      { label: "2026", value: 35 },
    ],
    actions: ["슈퍼 얼리버드 등록", "두바이 호텔 사전 예약", "투자자 미팅 리스트 준비"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 미공개",
      items: [{ name: "Side events not yet announced", host: "TBA", date: "2026-12-01", desc: "사이드 이벤트 미공개" }],
    },
  },
  {
    id: "bitcoin-mena-2026",
    name: "Bitcoin MENA 2026",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    date: "2026-12-07",
    endDate: "2026-12-08",
    days: 2,
    venue: "ADNEC Centre Abu Dhabi — Marina Hall",
    tier: "A",
    autoTier: "A",
    tierScore: 79,
    tierReasons: ["중동·북아프리카 프리미어 비트코인 행사", "2024 랜드마크 데뷔 후 성장", "3,000명 참석 예상"],
    gradient: "from-amber-100 via-white to-green-100",
    status: "upcoming",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=300&fit=crop",
    sideEventUrl: "https://luma.com/bitcoin-mena",
    website: "https://bitcoinmena.com/",
    cost: { flight: 780, hotel: 1300, transport: 160, meals: 380, ticket: 799, total: 3419 },
    summary: {
      features: ["중동·북아프리카 프리미어 비트코인 행사", "업계 전문가, 고액 자산가, 기관 투자자 집결", "아부다비 글로벌 디지털 자산 허브 위상 반영"],
      difference: ["MENA 지역 특화", "비트코인 단일 자산 집중", "아부다비의 디지털 자산 대화 영향력 반영"],
      pros: ["MENA 비트코인 네트워킹 최적", "아부다비 프리미엄 인프라", "기관 투자자 접근"],
      risks: ["글로벌 비트코인 행사 대비 규모 제한", "아부다비 숙박비 높음", "비트코인 외 프로토콜 관련성 낮음"],
      expectations: ["MENA 비트코인 채택 동향", "기관 투자자 네트워킹", "아부다비 규제 인사이트"],
    },
    feed: [
      { label: "2026 에디션 공식 발표", time: "3개월 전", type: "공지" },
      { label: "얼리버드 티켓 오픈", time: "2개월 전", type: "비용" },
      { label: "ADNEC Marina Hall 베뉴 확정", time: "4개월 전", type: "운영" },
    ],
    archive: {
      year: "2024",
      attendees: "2,000+",
      sideEvents: 5,
      sponsors: 30,
      media: 15,
      eventTitle: "Bitcoin MENA 2024",
      notes: ["랜드마크 데뷔 에디션", "아부다비 디지털 자산 대화 시작"],
    },
    kpis: [
      { label: "미팅 적합도", value: "높음", detail: "MENA/비트코인" },
      { label: "아카이브 성장", value: "+50%", detail: "참석자 YoY 예상" },
      { label: "업데이트 주기", value: "14일", detail: "90일 이내" },
    ],
    budget: [
      { label: "항공권", value: 780 },
      { label: "숙박", value: 1300 },
      { label: "티켓", value: 799 },
      { label: "현지비", value: 540 },
    ],
    sideEventTrend: [
      { label: "2024", value: 5 },
      { label: "2025", value: 8 },
      { label: "2026", value: 10 },
    ],
    actions: ["얼리버드 티켓 등록", "아부다비 호텔 사전 예약", "MENA 파트너 리스트 준비"],
    companies: [],
    sideEvents: {
      count: 0,
      label: "사이드 이벤트 미공개",
      items: [{ name: "Side events not yet announced", host: "TBA", date: "2026-12-07", desc: "사이드 이벤트 미공개" }],
    },
  },
];

export const events = [...eventData].sort((a, b) => a.date.localeCompare(b.date));

// 행사 기준 2일 전 ~ 종료일+2일 후까지 LIVE 윈도우
export function getEventLiveStatus(event: EventData): boolean {
  if (event.status === "cancelled") return false;
  const now = new Date();
  const start = new Date(event.date + "T00:00:00Z");
  const end = event.endDate ? new Date(event.endDate + "T23:59:59Z") : new Date(event.date + "T23:59:59Z");
  const liveStart = new Date(start.getTime() - 2 * 86400000);
  const liveEnd = new Date(end.getTime() + 2 * 86400000);
  return now >= liveStart && now <= liveEnd;
}
